### ISSUE TITLE
Significant slowdown when I query the index with mapping

### ISSUE THREAD

**Issue by SergeVil** [elastic/elasticsearch-hadoop#1017]
### Issue description

I run the same pyspark program on two indices with the almost same amount of data:

For vertex1 17.3Gi/34.3Gi 35.6M 
For other_vertex_2 19.3Gi/38.6Gi 35.6M

The first index (vertex1) does not have a mapping applied. It takes 9 mins to read.

The second index (other_vertex_2) has a mapping (see attached file) and it takes 38 mins to read. 

### Steps to reproduce
```
q_all ="""
    {"query":
        {"match_all": {}}
    }
   """

def readVerticesFromES(q, index, scrollLimit = "-1"):
    es_read_conf_vertex = {
        "es.nodes" : "myserver-04",
        "es.port" : "9200",
        "es.resource" : index,
        "es.query" : q,
        "es.scroll.limit" : scrollLimit
    }
    
    es_rdd_vertex = sc.newAPIHadoopRDD(
        inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
        keyClass="org.apache.hadoop.io.NullWritable",
        valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
        conf=es_read_conf_vertex)
            
    return es_rdd_vertex

if __name__ == '__main__':
    pass

    sparkConf = SparkConf().setAppName("ESTest")
    sc = SparkContext(conf=sparkConf)

    log4jLogger = sc._jvm.org.apache.log4j
    log4jLogger.LogManager.getRootLogger().setLevel(log4jLogger.Level.WARN)

    log = log4jLogger.LogManager.getLogger(__name__)

    vertRDDRead = readVerticesFromES(q_all, "other_vertex_2", "-1").cache()

    log.warn("vertRDDRead: %i" % vertRDDRead.count())

    sc.stop()
```
### Version Info

OS:         :  CentOS release 6.9 (2.6.32-642.4.2.el6.x86_64)
JVM         :  1.8.0_131 (Oracle Corporation)
Hadoop/Spark:  hadoop-2.7.3/spark-2.1.1 
ES-Hadoop   :  elasticsearch-hadoop-6.0.0.BUILD-20170608.170859-24.jar
ES          :  5.3.2 build_date: "2017-04-24T16:15:59.481Z"

**Comment by SergeVil** [comment]
Attached mapping 
[bug.json.txt](https://github.com/elastic/elasticsearch-hadoop/files/1156052/bug.json.txt)

**Comment by jbaiera** [comment]
I'm confused about what you mean by:
> The first index (vertex1) does not have a mapping applied.
If an index has data in it, it should have a mapping, whether it was set by the user or not... are the mappings drastically different?

I also noticed that you are not specifying a type on your elasticsearch resource. This can lead to issues with reading data since the connector has a bug with how it processes multiple mappings and indices without types provided. Could you include the `DEBUG` level logs from your jobs? I'm wondering if it's discovering the mapping incorrectly and thus is just skipping parsing fields altogether or if it's some other problem.

Please note that the multiple-mapping and typeless indexing bugs have a fix in the master branch right now: 093e9881665c496c4354c8d474ac551919355166

**Comment by SergeVil** [comment]
Hi James,

How should I setup my logging levels? Should I modify my pyspark code?

Thank you,
Serge

**Comment by jbaiera** [comment]
Setting logging levels is based on how you have spark deployed. The Spark documentation goes into detail on how to provide a log4j file: http://spark.apache.org/docs/latest/running-on-yarn.html#debugging-your-application

**Comment by SergeVil** [comment]
Which one do you mean:

log4j.rootCategory=INFO, console
log4j.logger.org.apache.spark.repl.Main=WARN

or any other?

**Comment by jbaiera** [comment]
You'll want to set the levels for the `org.elasticsearch.hadoop` packages to `TRACE`

**Comment by SergeVil** [comment]
Where are they specified?

I know only

log4j.logger.org.elasticsearch.hadoop.rest.commonshttp=TRACE

What are the other ones?

**Comment by jbaiera** [comment]
Log4J should inherit the log level for all classes under the given package name. I don't think you'll need to specify anything other than that.

**Comment by SergeVil** [comment]
Please, see attached.

I included mappings created using the commands like:
curl –XGET 'localhost:9200/vertex1/_mapping' > vertex1.map
and traces created with log4j.logger.org.elasticsearch.hadoop=TRACE

[serge_logs.zip](https://github.com/elastic/elasticsearch-hadoop/files/1162644/serge_logs.zip)

**Comment by jbaiera** [comment]
Thanks for the logs! The big thing that I've noticed is that you are not specifying any type names with your indices: When ES-Hadoop tries to discover the mappings for your index, it is only reading ONE mapping from the list of types, which could be causing inconsistent time spent serializing. Here's an example:

```
17/07/18 14:12:56 DEBUG EsInputFormat: Discovered mapping {convert_long_to_double=[description=TEXT, graph_uuid=KEYWORD, ingest_time=DATE, label=KEYWORD, location=GEO_POINT, provenance_uuid=KEYWORD, provider=KEYWORD, relationships=[type=KEYWORD, uuid=KEYWORD], time=[start_time=DATE, start_timestamp=DATE, stop_time=DATE, stop_timestamp=DATE], title=TEXT, type=KEYWORD, uuid=KEYWORD]} for [other_vertex_2]
```

Here, when reading data from `other_vertex_2` index, unless the data being read matches those field names, it won't be deserialized. Notice how the only type pulled is the `convert_long_to_double` type. Compare with reading the `vertex1` index:

```
17/07/18 14:05:15 DEBUG EsInputFormat: Discovered mapping {reddit_subreddit=[data=[name=TEXT], domain=KEYWORD, id=KEYWORD, ingest_time=TEXT, type=KEYWORD]} for [vertex1]
```

Another item that pops out to me here is that the slice logic is giving you a very large number of input splits:

```
17/07/18 14:05:16 INFO EsInputFormat: Created [355] splits
```

But inspecting the scroll responses, many of them are coming up empty. Perhaps it makes sense to increase the `es.input.max.docs.per.partition` to be 1,000,000 instead of 100,000. To bring down the amount of tasks that are spinning up, doing nothing and then tearing down.

Finally, I would try retesting on one of the more recent snapshots. There is a fix in master to handle the above problem of only working with one type at a time: 093e9881665c496c4354c8d474ac551919355166. Maybe this will give a more consistent reading performance when serialization is involved.

**Comment by SergeVil** [comment]
James, thank you for the analysis! 

I tried to increase es.input.max.docs.per.partition, but it worked worse, so I tried to decrease it to 10,000 and it worked better. The first index scanning time increased to 11 minutes, but the second time decreased to 19 minutes (twice faster). I notice no dead Spark tasks like I saw before. 

I have two questions. What do you mean by "reading ONE mapping from the list of types"? Can you explain, please? From the log I see it reads the mapping. Another question is if you can point me out on the last snapshot. I cannot find it here: https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-hadoop/

Cheers!
Serge

**Comment by SergeVil** [comment]
I also tried with type "dblp_author". 

The vertex1/dblp_author took me 2.3 minutes, while other_vertex_2/dblp_author took me 3.3 minutes.

**Comment by jbaiera** [comment]
@SergeVil the `index.max_slices_per_scroll` setting is an index level property. I would avoid increasing it above 1024, as that may have negative side effects on your Elasticsearch cluster. Instead, I would tune your `es.input.max.docs.per.partition` value to keep the number of tasks below that number.

When I say "reading ONE mapping from the list of types" I mean that Elasticsearch indices can have multiple types in the 5.x versions and below. Normally when you execute a search (or in ES-Hadoop's case a scrolled search) you specify the type name to execute against. If you do not specify a type name to execute against, then the search is performed against ALL data for ALL types under the given index. In ES-Hadoop, when we get in a piece of JSON to deserialize, we need to know what kind of field type that data is. At the start of the job, we try and discover the mappings for the given index and type. There was a bug previously in the connector where we would only use the first mapping returned for an index if no type was specified. Any data that did not conform to that mapping is just thrown out. There's a new commit in master that addresses this problem for 6.0 and will most likely be backported to the 5.x line.

As for the snapshots not being found, I'll see if I can dig into why they haven't been updated in a while. I am guessing that it may have to do with the last alpha release.

> I changed the query as:
> {
> "_source": ["type", "id", "ingest_time"],
> "query": {"match_all": {}}
> }
> to avoid the nested data structures ("data" field contains some), but got same results.

Specifying the source field filtering in that way is no longer supported as of 5.x. We made some changes that make query parsing more strict. Instead of that, I would use the new property for specifying source filtering: `es.read.source.filter` (as described [here](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#configuration-options-index))

**Comment by jbaiera** [comment]
@SergeVil To be clear: The issue with multiple types relates to #938 and #850 and was solved in 093e9881665c496c4354c8d474ac551919355166

**Comment by jbaiera** [comment]
@SergeVil To address your comment about the snapshot:
> Another question is if you can point me out on the last snapshot. I cannot find it here: https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-hadoop/

I'm not sure why it's not displaying the artifacts, but it is indeed there. If you include `6.0.0.BUILD-SNAPSHOT` as the version in your build script it should be pulled down just fine.

**Comment by SergeVil** [comment]
James,

If I query comma separated multi-type, may it help to improve the performance? (https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-index-multi-type.html)

I need to query several types at once.

**Comment by jbaiera** [comment]
@SergeVil As long as you are using the snapshot that contains 093e988 in it, then it's possible that you could see a speed up by stating the types directly. If you have many types but only want to read from a subset of those, it can help with performance. The connector would ignore any data that does not belong to the types you have explicitly specified. If you are reading all the types on an index, then it might not save much time. 

To elaborate why that commit is important: When the connector reads data, it discovers the mapping for the types it is about to read. This allows the connector to convert the JSON data from Elasticsearch into consistent field types in Spark. If a field is not in the discovered mapping, then the connector discards it, and it shows up as `null`. There was a bug in previous versions of the connector that would only read _one_ of the mappings from the list of types you were targeting. This caused the connector to skip deserializing data from any other types.

My guess here for why you might be seeing a performance discrepancy is that one read operation is getting data from a type that matches more of the discovered fields than the other read operation. If the connector correctly discovers all mappings for each type, then it should not ignore any of the fields that it is reading from Elasticsearch. In this case, you should see more consistent read speeds between the read operations. This may not be necessarily faster, but it is a more accurate reading of the data from Elasticsearch.

**Comment by jbaiera** [comment]
I'm going to go ahead and close this for now since the conversation has seemed to die down. If anything comes up we can easily re-open this and recommence the conversation.
