### ISSUE TITLE
Cannot find 7.0.0-alpha1-SNAPSHOT/maven-metadata.xml and friends

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch-hadoop#1077]
The periodic master builds of are now failing because they're trying to download a `7.0.0-alpha1-SNAPSHOT` version from Maven which does not exist for obvious reasons.

e.g. https://elasticsearch-ci.elastic.co/view/Elasticsearch/job/elastic+elasticsearch-hadoop+master+periodic/425/console

It's possible (likely) this is due to https://github.com/elastic/elasticsearch/pull/27397 which changes the way that version numbers are handled in the build system.

**Comment by jbaiera** [comment]
Thanks @DaveCTurner. This should be fixed in https://github.com/elastic/elasticsearch-hadoop/commit/993e691c56174795eaad99977b69364398e9da70.

7.0.0-alpha1-SNAPSHOT should be getting published nightly, and is a valid version number in [the list of snapshots on maven](https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch/maven-metadata.xml), but our repository info for Lucene snapshots was out of date. Additionally, it seems that the CLI module for Elasticsearch was not found. We don't depend on anything there so I've excluded it.
