### ISSUE TITLE
Not able to fetch a property which is not present in the elastic index mapping

### ISSUE THREAD

**Issue by jrmbrgs** [elastic/elasticsearch-hadoop#1131]
### What kind an issue is this?
- [x] Bug report

### Issue description

Not able to fetch a property which is not present in the elastic index mapping.
Even if the custom DF schema provided includes the property missing in the ES mapping.

### Steps to reproduce
Here is the mapping:
```JSON
{
"availability_17.30": {
        "mappings": {
            "details": {
                "dynamic": "false",
                "dynamic_templates": [
                    {
                        "disable_all_fields_analyzing": {
                            "mapping": {
                                "index": "no"
                            },
                            "match": "*"
                        }
                    }
                ],
                "_timestamp": {
                    "enabled": true,
                    "store": true
                },
                "properties": {
                    "sale_id": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}
```

Here is the doc:
```JSON
{
                "_index": "availability_17.30",
                "_type": "details",
                "_id": "jb",
                "_score": 1,
                "_source": {
                    "sale_id": 1234,
                    "foo": "bar"
                }
            }
```

Code:

```SCALA
import org.elasticsearch.spark._
import org.elasticsearch.spark.sql._
import org.apache.spark.sql.SQLContext
import org.apache.spark.sql.types.{IntegerType, ArrayType, StringType, StructField, StructType}

val sql = new SQLContext(sc)
val esConfig = Map("es.nodes" -> "xxx",
    "es.port" -> "9200",
    "es.query" -> "?q=_id:jb",
    "es.read.field.include" -> "sale_id,foo"
)

val schema = StructType(
        StructField("sale_id", IntegerType, true) ::
        StructField("foo", StringType, true) :: Nil
)

val df = sql.read.schema(schema).format("org.elasticsearch.spark.sql").options(esConfig).load("availability_17.30/details")

println(df.schema.treeString)

df.show()
```

Strack trace:

```
scala> println(df.schema.treeString)
root
 |-- sale_id: integer (nullable = true)
 |-- foo: string (nullable = true)

scala> df.show()
2018-03-30 12:29:26 WARN  ScalaEsRowRDD:70 - Field(s) [foo] not found in the Elasticsearch mapping specified; did you mean [<no-similar-match-found>]?
+-------+----+
|sale_id| foo|
+-------+----+
|   1234|null|
+-------+----+
``` 

### Version Info

OS         :  OSX 
JVM         :  1.8
Hadoop/Spark:  2.2
ES-Hadoop   :  tried with 2.4, 5.3.x and 6.2.3
ES          :  1.5.2

**Comment by jrmbrgs** [comment]
I finally found an undocumented ES option : es.read.unmapped.fields.ignore

https://github.com/elastic/elasticsearch-hadoop/blob/5.3/mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java#L219-L220

Could be helpful to add it it doc https://www.elastic.co/guide/en/elasticsearch/hadoop/6.2/configuration.html

**Comment by jbaiera** [comment]
@jrmbrgs I'm not entirely sure that option is going to help. When the connector starts up, it discovers the Elasticsearch mapping so that it can match each field name to the data type that will be returned from ES. These data types are used during the scroll reading process, and in the event that the setting you mentioned is set to false, the parsing will simply continue using a `null` field type for that field name. Most of our serialization code treats a `null` field type as an error case at worst, or returns a null value at best.

Unfortunately, the schema provided to Spark is not used at this low level, as the code that performs this reading is integration agnostic. I'm not sure I see the use case here of leaving data off of a mapping and then expecting to read it back effectively. While it is possible to pull that data from the schema, merging schemas between two technologies can be rife with problems and exceptions to rules. Can you elaborate more on what you're trying to do here?

**Comment by jrmbrgs** [comment]
Hello @jbaiera,
Thx for your quick reply (and for your work on ES  Hadoop).

About my use case, to sum up, I've heavy and deep documents stored in ES, around 8Mo/ 500k+ lines a doc.
Because of the doc structure complexity, I don't index each property in the ES index mapping. I only index property which are supposed to be used for search. (just like in a classic RDMBS we do not index all cols). Doing that I'm reducing the index needed storage space and preserving the write perf.
By the way, the ES REST API returns the whole docs with all properties according to the given search, not only those which are declared the mapping.

By setting `es.read.unmapped.fields.ignore` to `false` I was able to fetch back not mapped properties but only those at the 1st level of the document tree.

I was able to fetch any not mapped props by using the user defined struct (if provided) in stead of the discovered mapping in `DefaultSource.scala`.

I've just pushed the patch if you want to give a look.
https://github.com/elastic/elasticsearch-hadoop/compare/5.3...jrmbrgs:reading_unmapped_props?expand=1
I did it for the 5.3 but also successfully tried on 6.x and 7-alpha.

There are probably some impacts I did not anticipate, feel free to give me any feedback.

**Comment by ebuildy** [comment]
Hello @jrmbrgs , this is possible via RDD instead DataFrame.

```
import org.elasticsearch.spark.rdd.EsSpark

val rdd = EsSpark.esJsonRDD(sc, "availability_17.30/details", Map("es.nodes" -> "XXX:9200"))

val rdd2 = rdd.map(f => f._2)

val df = sqlContext.read.json(rdd2)

df.show
```

(code tested with Spark 1.6.2 / ES 2.4)

**Comment by jbaiera** [comment]
This sort of problem with unmapped fields manifests itself when using an object field set with "enabled" to false, as described in issue #1117:

The issue here is that when enabled is set to false, Elasticsearch does not persist any information about the field, and thus does not list any child fields under the object in the mapping. The lack of child fields causes issues in the connector when it encounters the extra_tags field, since it is about to read a piece of data and that data must be added to the extra_tags structure, but it does not know where to place the data in the row's field order because there is no information about any child fields under it.

**Comment by jbaiera** [comment]
Closing this out since the conversation has trailed off. If any parties involved in the discussion feel like more concrete actions should be discussed, we can re-open.
