### ISSUE TITLE
Support for signing requests for AWS Elasticsearch

### ISSUE THREAD

**Issue by prashs** [elastic/elasticsearch-hadoop#1140]
### What kind an issue is this?

- [x] Feature Request. 

### Issue description
If we want to fetch or write data to/from an AWS Elasticsearch setup, there is a need to sign requests as per the below documentation:

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html#es-managedomains-signing-service-requests

As far as I understand, this is not supported by the "elasticsearch-hadoop" library as of now. If spark is running on AWS, one could configure IP address/host based IAM policies, but if data needs to be accessed from outside of AWS, there is not a good solution for this as far as I know.

The ES proxy (https://github.com/abutaha/aws-es-proxy) might be a possible way to get around this, but the problem there is that the infrastructure teams usually hesitate to provide tools that anybody can access without authenticating and dev teams don't really want to maintain things like this proxy.

### Version Info

OS:         :  Centos 6.8
JVM         :  1.8
Hadoop/Spark: Spark 2  
ES-Hadoop   :  6.2.4
ES          :  AWS ES 5.5

### Feature description
See description above

**Comment by jbaiera** [comment]
Hi @prashs, thanks for opening an issue for this. We currently have an issue that covers this problem at #626. If you would like to add any information on to that issue as well as any +1's that would be great.

Since we have an issue open for this already, I'll go ahead and close this. Let me know if there's any reasons you feel like this should be re-opened and I'd be happy to take a look.
