### ISSUE TITLE
Using org.elasticsearch.hadoop with Searchguard

### ISSUE THREAD

**Issue by stevensuting** [elastic/elasticsearch-hadoop#1195]
Is this feature available:
Currently there are provision to use keystore, is there a way to use pem?

### Issue description
I am trying to connect to ES from spark. It worked fine until Searchguard(Version:6.4.1-23.1) was installed. As per the documentation https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_basic_authentication the user and pass parameters needed to be passed.

    es_write_conf = {
        "es.nodes" : "192.168.22.22",
        "es.port" : "9200",
        "es.input.json": "true",
        "es.nodes.ingest.only": "true",
        "es.net.http.auth.user": "user",
        "es.net.http.auth.pass": "pass"
    }

Function being used:

    saveAsNewAPIHadoopFile(
    path='-',
    outputFormatClass="org.elasticsearch.hadoop.mr.EsOutputFormat",
    keyClass="org.apache.hadoop.io.NullWritable",
    valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
    conf=es_write_conf)

However, even after doing so it does not connect and throws the following error:

    18/09/27 10:59:28 INFO HttpMethodDirector: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server 192.168.22.22 failed to respond
    
    18/09/27 10:59:29 ERROR NetworkClient: Node [192.168.22.22:9200] failed (The server 192.168.2.59 failed to respond); no other nodes left - aborting...
    
    Caused by: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[192.168.22.22:9200]]

### Version Info
OS:         :  Centos 7
JVM         :  1.8
Hadoop/Spark:  2.3.1
ES-Hadoop   :   elasticsearch-hadoop-6.3.2.jar
ES          :  6.4.1
Search Guard: 6.4.1-23.1

**Comment by jbaiera** [comment]
We don't do any testing against Searchguard since it's a third party plugin, so I'm not sure I can comment on or guarantee how stable ES-Hadoop's interactions with it are. In this case I looks like the server side of the connection is not responding to the request, so I would check to see if there is any information in the logs on the server side. Additionally, I notice that your settings do not include any SSL options, which may be required to perform basic authentication over HTTP.

Since this is a third party plugin issue, I'm going to close this issue for now. I'm happy to re-open it if you are able to diagnose the problem further and can pin down something that the connector is doing that should be improved or corrected.
