### ISSUE TITLE
ip specified in es.nodes is being converted to some other ip I can't recognize..

### ISSUE THREAD

**Issue by littlehome-eugene** [elastic/elasticsearch-hadoop#1267]
### What kind an issue is this?

- [ x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

### Steps to reproduce
try to connect remote elasticsearch by using `es.nodes`

Code:

```
     conf = pyspark.SparkConf()
     conf.set("spark.driver.allowMultipleContexts", "true")
     conf.set("es.index.auto.create", "true")
+    # conf.set('es.nodes.wan.only', 'true')
+    conf.set("es.http.timeout", "10s")
     conf.set("es.nodes.discovery", "true")
     conf.set("es.read.field.exclude", "data.integrations")
+    conf.set("es.nodes", "192.168.0.7")
```
I see output 
```
2019-03-28 19:41:18 ERROR NetworkClient:147 - Node [172.17.0.1:9200] failed (The host did not accept the connection within timeout of 10000 ms); selected next
 node [192.168.0.7:9200]
2019-03-28 19:41:28 ERROR NetworkClient:147 - Node [172.17.0.1:9200] failed (The host did not accept the connection within timeout of 10000 ms); no other node
```
s left - aborting...

I specified `192.168.0.7` as es.nodes, but it is trying `172.17.0.1`  and fails to connect...

When I ssh to `192.168.0.7` or telnet, or curl, it works all fine. just `elasticsearch-hadoop` is changing the ip to `172.17.0.1` and fails to connect..

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by liansghuaifan** [comment]
me too ，did you solved？

**Comment by liansghuaifan** [comment]
i add .config("es.nodes.discovery", false ) can solve . hope help you

**Comment by jbaiera** [comment]
If the Elasticsearch node is on a private network, it may serve IP addresses to clients during the discovery process that ES-Hadoop will not be able to reach. In these cases, discovery should be disabled for the cluster and all node addresses should be provided to the ES-Hadoop. If the cluster is behind some sort of reverse proxy or load balancer that acts as a gateway for the cluster, then wan only mode should be enabled. Wan only mode simply disables both node discovery and node filtering. Only the addresses provided will be used for communication, and ES-Hadoop will not attempt to optimize communication with them based on their roles, because those node characteristics are not available to it.

Closing this since it seems to be a configuration/environmental issue.
