### ISSUE TITLE
Find Lucene version automatically

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch-hadoop#1321]
Replace the manual setting of Lucene's version in `esh-version.properties` file with a mechanism that finds it automatically through ES version.

Currently when Lucene is updated the version should be updated in this repo as well manually, which can be the source of build failures.

See for example #1320.

**Comment by atorok** [comment]
The hadoop build already uses `build-tools` so could be looking at version.properties ( there's also a `VersionProperties` class ) to figure out the lucene version.

**Comment by matriv** [comment]
@atorok When I tried the VersionProperties I get `8.0.0` for lucene:
![Screenshot 2019-07-17 at 16 52 21](https://user-images.githubusercontent.com/5058131/61381139-4878cf00-a8b3-11e9-84ae-5b251924cdce.png)

**Comment by atorok** [comment]
Maybe the wrong version of build-tools is being pulled in ? Or a snapshot that doesn't have the update yet.

**Comment by matriv** [comment]
I tried `7.2.0.` version of build tools but still I get `8.0.0` from `VersionProperties.lucene`.
Do you mean could something be wrong with es version?

**Comment by jbaiera** [comment]
The manual versioning for Lucene is tied to the fact that the build-tools artifact is no longer java 8 compliant. The decision at the time of it breaking was to hard code ES-Hadoop to use an older version of build-tools in order to unblock daily snapshots. The escape valves for lucene and build tools versions were added at that time. I've gone through and tried undoing the original hack but it seems that the build tools are still java 11 only on 7.x.

**Comment by jbaiera** [comment]
Closing this as I don't think we pull the lucene artifacts for the project any longer.
