### ISSUE TITLE
Version check fails on SpringBoot applications

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1359]
It seems that the Spring Boot plugin includes the dependencies of the jars in your project nested inside the final jar. This is causing a "hierarchical URI exception."

When ES-Hadoop is first loaded, it runs some checks within the Version class that ensure that only one copy/version of ES-Hadoop is available on the classloader. This is to ensure no Jar-Hell issues while running (which was more common than one would think without the check).

To verify that condition, the ES-Hadoop asks the current classloader for all copies of the Version class that it knows about. The classloader returns a set of URL's (either jars or .class files) that are then validated by ES-Hadoop to ensure no duplicates. We canonicalize each URL to eliminate false duplicates, like if a jar appears twice because of symlinks in the classpath. Finally, if only one unique URL remains, we can be sure that there's only one ES-Hadoop library available and the check passes.

The issue here is that the location of the jar file that ES-Hadoop finds is within another jar file, which cannot be resolved as a canonical filepath because it is inside an archive file. In this case, the ES-Hadoop jar is located at:
```
file:///path/to/agensspark-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/elasticsearch-hadoop-7.3.2.jar
```
... which is not a hierarchical URI.

**Comment by jbaiera** [comment]
Supercedes #1358

**Comment by wboult** [comment]
For those experiencing this issye and using Gradle to build your spring boot application, the following configuration of the `bootJar` gradle task is a simple workaround:

```groovy
bootJar {
  requiresUnpack '**/elasticsearch-spark-*.jar'
}
```

**Comment by Leme34** [comment]
Here's my problem is ：
java.lang.ClassNotFoundException: org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1

Here's the stack trace:

server_1                     | 2020-03-08 06:33:16.725 ERROR 1 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 18.0 failed 4 times, most recent failure: Lost task 2.3 in stage 18.0 (TID 1440, 172.23.0.2, executor 0): java.lang.ClassNotFoundException: org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1
server_1                     |  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
server_1                     |  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
server_1                     |  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
server_1                     |  at java.lang.Class.forName0(Native Method)
server_1                     |  at java.lang.Class.forName(Class.java:348)
server_1                     |  at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
server_1                     |  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819)
server_1                     |  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
server_1                     |  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
server_1                     |  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
server_1                     |  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
server_1                     |  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155)
server_1                     |  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
server_1                     |  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
server_1                     |  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
server_1                     |  at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
server_1                     |  at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
server_1                     |  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:80)
server_1                     |  at org.apache.spark.scheduler.Task.run(Task.scala:99)
server_1                     |  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
server_1                     |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
server_1                     |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
server_1                     |  at java.lang.Thread.run(Thread.java:745)
server_1                     |
server_1                     | Driver stacktrace:] with root cause
server_1                     |
server_1                     | java.lang.ClassNotFoundException: org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1
server_1                     |  at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_242]
server_1                     |  at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_242]
server_1                     |  at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_242]
server_1                     |  at java.lang.Class.forName0(Native Method) ~[na:1.8.0_242]
server_1                     |  at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_242]
server_1                     |  at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67) ~[spark-core_2.11-2.1.2.jar!/:2.1.2]
server_1                     |  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[na:1.8.0_242]
server_1                     |  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[na:1.8.0_242]
server_1                     |  at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75) ~[spark-core_2.11-2.1.2.jar!/:2.1.2]
server_1                     |  at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114) ~[spark-core_2.11-2.1.2.jar!/:2.1.2]
server_1                     |  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:80) ~[spark-core_2.11-2.1.2.jar!/:2.1.2]
server_1                     |  at org.apache.spark.scheduler.Task.run(Task.scala:99) ~[spark-core_2.11-2.1.2.jar!/:2.1.2]
server_1                     |  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322) ~[spark-core_2.11-2.1.2.jar!/:2.1.2]
server_1                     |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_242]
server_1                     |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_242]
server_1                     |  at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_242]


I have tried maven and gradle requirementsUnpack still not working,Could some one help me please?

**Comment by masseyke** [comment]
Does anyone have concrete steps to reproduce this one?
