### ISSUE TITLE
Feature request, support multi url for HA

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch-hadoop#1367]
Is it make sense to support multi hdfs url config, in some case, the Hadoop is only configured as ip, and right now there is only one url can be set:

![image](https://user-images.githubusercontent.com/64487/66831171-a936a700-ef89-11e9-840b-ad09b52ce593.png)

And for HA purpose, if this config can accept a url array, will be better, like this:
```
PUT _snapshot/my_hdfs_repository
{
  "type": "hdfs",
  "settings": {
    "uri": ["hdfs://192.168.1.10:8020/","hdfs://192.168.1.11:8020/"],
    "path": "elasticsearch/repositories/my_hdfs_repository",
    "conf.dfs.client.read.shortcircuit": "true"
  }
}
```

**Comment by jbaiera** [comment]
The current hdfs repo does support HA namenode, though it must be configured to do so through the available HA [configurations](https://hadoop.apache.org/docs/r2.7.5/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithNFS.html#Configuration_overview) for HDFS, namely the `dfs.nameservices` property and all related configurations to it. This is the only way for accessing HA namenode services via the HDFS Repository as the configurations are same across both the Hadoop deployment and the repository definition. 

FYI, In the future, hdfs repository issues should be opened on the [Elasticsearch repository](https://github.com/elastic/elasticsearch), since that is where it lives now a days.

**Comment by gowthamhub** [comment]
> Is it make sense to support multi hdfs url config, in some case, the Hadoop is only configured as ip, and right now there is only one url can be set:
> 
> ![image](https://user-images.githubusercontent.com/64487/66831171-a936a700-ef89-11e9-840b-ad09b52ce593.png)
> 
> And for HA purpose, if this config can accept a url array, will be better, like this:
> 
> ```
> PUT _snapshot/my_hdfs_repository
> {
>   "type": "hdfs",
>   "settings": {
>     "uri": ["hdfs://192.168.1.10:8020/","hdfs://192.168.1.11:8020/"],
>     "path": "elasticsearch/repositories/my_hdfs_repository",
>     "conf.dfs.client.read.shortcircuit": "true"
>   }
> }
> ```

did u able to setup multi hdfs url config ?

**Comment by gowthamhub** [comment]
> The current hdfs repo does support HA namenode, though it must be configured to do so through the available HA [configurations](https://hadoop.apache.org/docs/r2.7.5/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithNFS.html#Configuration_overview) for HDFS, namely the `dfs.nameservices` property and all related configurations to it. This is the only way for accessing HA namenode services via the HDFS Repository as the configurations are same across both the Hadoop deployment and the repository definition.
> 
> FYI, In the future, hdfs repository issues should be opened on the [Elasticsearch repository](https://github.com/elastic/elasticsearch), since that is where it lives now a days.

could you explain this more elaborate
