### ISSUE TITLE
 Dynamic resources are supported only for writing

### ISSUE THREAD

**Issue by jackmanwu** [elastic/elasticsearch-hadoop#1614]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Dynamic resources are supported only for writing, for doing multi-index/type reads, use an appropriate search query.
What should I do to reda?

### Steps to reproduce

Code:

```
                  CREATE
EXTERNAL TABLE `recommend_users`
(
    `uid`  BIGINT,
    `task_date`  STRING
)PARTITIONED BY (`day` string)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'recommend_users_{task_date}/recommend_users',
    'es.index.auto.create' = 'true',
    'es.nodes' = 'http://xxxxx',
    'es.port'='9200',
    'es.net.http.auth.user'='xxx',
    'es.net.http.auth.pass'='xxx'
)
```

Strack trace:

```
Failed with exception java.io.IOException:org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot read indices that have curly brace field extraction patterns in them: recommend_users_{task_date}
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  3.2.1
ES-Hadoop   :  7.11.1
ES          :  5.5.1
Hive.      : 3.2.1

**Comment by jbaiera** [comment]
Using dynamic resources is a little odd with integrations like Hive where the integration is expressed as a read/write data store. In most integrations we support, the index name is specified at the point where the read operation or write operation is defined.

We have two [configurations](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html) that should help: `es.resource.read` and `es.resource.write`. In this case, instead of setting just `es.resource` you could try setting `es.resource.write` to be `recommend_users_{task_date}/recommend_users` and set `es.resource.read` to be `recommend_users_*/recommend_users`.
