### ISSUE TITLE
Spark mode overwrite not working when using Dynamic/multi resource writes

### ISSUE THREAD

**Issue by dlubomski** [elastic/elasticsearch-hadoop#1622]
### Issue description

Spark mode overwrite not working when using Dynamic/multi resource writes.
Data in Elastic are duplicated not overwritten.

### Steps to reproduce

Code:

```
    df.write.format("org.elasticsearch.spark.sql"). \
        option("es.resource", "my_index-{date_bucket}"). \
        option("es.nodes.wan.only", "true"). \
        option("es.http.timeout", "3m"). \
        option("es.port", "920"). \
        option("spark.es.net.http.auth.user", ""). \
        option("spark.es.net.http.auth.pass", ""). \
        option("es.nodes", "http://elastic.abc.com"). \
        mode("overwrite").save()
```
This code working as expected:

```
    df.write.format("org.elasticsearch.spark.sql"). \
        option("es.resource", "my_index"). \
        option("es.nodes.wan.only", "true"). \
        option("es.http.timeout", "3m"). \
        option("es.port", "920"). \
        option("spark.es.net.http.auth.user", ""). \
        option("spark.es.net.http.auth.pass", ""). \
        option("es.nodes", "http://elastic.abc.com"). \
        mode("overwrite").save()
```

### Version Info

Hadoop/Spark:  Spark 3.1.1
ES-Hadoop   :  elasticsearch-spark-30_2.12-7.13.0-20210303.042227-17.jar
ES          :  7.7.1

**Comment by jbaiera** [comment]
The connector attempts to delete data before saving a dataframe when using the `overwrite` mode. The deletion operation takes place on the job driver before any tasks are submitted. The job driver isn't able to resolve the index pattern into a real index name because it doesn't have any records to pull values from. In this scenario, the driver simply treats the patterned index as a plain index name and checks if it exists. Since no index exists with that plain index name, the driver skips the deletion phase and just runs the job.

We should be detecting this configuration problem at runtime and throw an exception. It's possible that we could expand patterned resources into a glob pattern (use `*` in place of the pattern placeholders), but that should probably be controllable with a setting of some sort.

**Comment by jbaiera** [comment]
I opened #1637 to better capture this problem. Closing this issue in the mean time.
