### ISSUE TITLE
Hide sensitive credentials in Spark History

### ISSUE THREAD

**Issue by pablojimeneznext** [elastic/elasticsearch-hadoop#1633]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [X] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Feature description

We are trying to connect Spark 3.0.1 with Elasticsearch using the Elastic-hadoop library 7.12.0. Everything works fine.
However, we are using Spark History server to track jobs. Having a look at the SQL upper tab and seeing the explain details shows the following:
![dbbd0529711a5f22460f2d22e7bc206f0cade6b1](https://user-images.githubusercontent.com/81556451/112807884-b14cae80-9078-11eb-9370-a903e67df83b.png)

As you can see, it is showing the user and password which is not very safe :neutral_face:

We know it is possible to use a keystore: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/security.html#keystore
But we are retrieving at runtime those credentials. So, we cannot generate the keystore before running the job in Kubernetes.

I think that the Map that is printed in the Spark History shouldn't show user, password, and any other field that can be added to the keystore, since they are sensitive data.

**Comment by jbaiera** [comment]
At the moment, the keystore is the only supported route for providing sensitive configurations like these outside of plain text in the job configuration. This is because it is useable across all integrations we support.

Since you are pulling credentials to use at runtime, you might be able to make use of the Keytool program from inside your driver job to create and populate the keystore before submitting the job. 

The most supported way to do this would be to fork a process to run the keytool program from the ES-Hadoop jar, but forking is not always an option. Less supported (because the underlying code may change) would be to use the `org.elasticsearch.hadoop.cli.Keytool` class to construct the keystore from the same driver process. 

Alternatively, `org.elasticsearch.hadoop.cli.Keytool` simply calls into the project's `org.elasticsearch.hadoop.security.KeystoreWrapper` which has a better API for programming against, but isn't considered a public facing API (so once again, changes may occur in minor releases, though possibly unlikely). You could generate a temporary keystore for your job with something like this:

```java
KeystoreWrapper keystore = KeystoreWrapper.newStore().build();
keystore.setSecureSetting("es.net.http.auth.user", username);
keystore.setSecureSetting("es.net.http.auth.pass", password);
keystore.saveKeystore("file:///path/to/temporary/keystore/file")
```

I'll close this for now since this should work for the cases where credentials are loaded at runtime. Perhaps we could document this code in the security section for people who might find it useful.
