### ISSUE TITLE
ES-Hadoop does not correctly read from frozen indices

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1734]
Indices can be frozen in order to limit the resource consumption on a node. These frozen indices use special implementations that open the index for certain operations and then re-closes it when those operations complete. Part of this interaction requires the use of the `ignore_throttled` query parameter, which informs Elasticsearch to not skip the slower frozen indices when performing search operations. ES-Hadoop does not currently send this parameter along with requests, and thus frozen indices are incorrectly observed to contain zero records, and also break read tasks when the search request does not return a scroll id.

**Comment by masseyke** [comment]
There are a couple of things we need to do here:

1. Don't blow up if your query hits a frozen index
2. Make it configurable to be able to add `ignore_throttled` to a query to read in data from frozen indices.

The PR I just put up is for the first one. It treats frozen indices as if they are empty, but at least doesn't cause the task to fail in case a frozen index is just one of many indices you are reading. The second one might not be worth fixing since frozen indices are deprecated. For what it's worth (in case we want to add this at some point), I did add `ignore_throttled` to uriParams locally in org.elasticsearch.hadoop.rest.SearchRequestBuilder::assemble, and it pulled back the data from my test frozen index as expected.

**Comment by masseyke** [comment]
I'm closing this one since we no longer blow up on frozen indices. We won't add a parameter to be able to read from them because [freezing indices was deprecated in 7.14](https://www.elastic.co/guide/en/elasticsearch/reference/7.14/freeze-index-api.html).
