### ISSUE TITLE
Issue to re-open issue 853

### ISSUE THREAD

**Issue by asapegin** [elastic/elasticsearch-hadoop#1928]
The issue 853 was closed as "wontfix" without a proper reasoning. I.e. it was offered to "convert your field names with dots to object structures". However, ECS fields and Elastic SIEM rules were not converted to the object structures!

Please reopen issue 853 at least until ECS and rules will be converted as you proposed.

**Comment by asapegin** [comment]
Hi @masseyke. Sorry, but I'm confused with your request. How the ingest pipeline is potentially related to the https://github.com/elastic/elasticsearch-hadoop/issues/853 ? Since ingest pipelines has nothing to do with that issue, it is not possible to reproduce the problem with it.

**Comment by masseyke** [comment]
The problem is actually the _source field in the documents, not in the mapping. For example if I try to create a mapping for #853 like this:
```
curl -X PUT "localhost:9200/test4?pretty" -H 'Content-Type: application/json' -d'
{
  "mappings": {
   "properties":{
      "b":{
         "type":"integer"
      },
      "e":{
         "properties":{
            "f.g":{
               "fields":{
                  "keyword":{
                     "ignore_above":256,
                     "type":"keyword"
                  }
               },
               "type":"text"
            }
         }
      }
   }
}
}
'
```
then when I check it I get this:
```
curl -XGET localhost:9200/test4/_mapping | python -mjson.tool
{
    "test4": {
        "mappings": {
            "properties": {
                "b": {
                    "type": "integer"
                },
                "e": {
                    "properties": {
                        "f": {
                            "properties": {
                                "g": {
                                    "fields": {
                                        "keyword": {
                                            "ignore_above": 256,
                                            "type": "keyword"
                                        }
                                    },
                                    "type": "text"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
The mapping is actually stored as nested field, not the way we specified it with dots in the field names. The problem comes when I post data. I can either do it with dots in the field names like:
```
curl -XPOST localhost:9200/test4/_doc -H 'Content-Type: application/json' -d '{"b":0,"e":{"f.g":"hello"}}'
```
or as nested fields like:
```
curl -XPOST localhost:9200/test1/_doc -H 'Content-Type: application/json' -d '{"b":0,"e":{"f":{"g":"hello"}}}'
```
Either way Elasticsearch indexes them the same (in the way that matches the mapping), except that it keeps that original input as the `_source` field. It is this `_source` field that is tripping up es-hadoop. Keeping up with which document had its source in which format would be pretty tricky. We discussed just rewriting any document we come across in the nested format rather than dotted. But we have a pretty strong precedent of not tinkering with users' `_source` data because users might be relying on that for some external application.
This brings me to ingest pipelines. Regardless of your mapping, you can store the `_source` field without the dotted format. I would not be surprised at all if we are delivering some pipelines out of the box that don't convert the source to use the nested format. I'd like to prioritize fixing ones that are impacting people. If you are using one that is causing this problem I'd like to address it first.

**Comment by asapegin** [comment]
Please let me try to clarify my problem. Elastic Security is completely based on your ECS schema, which contains field names with dots. Ingest via filebeat, winlogbeat, etc. works without any problems, of course. However, when I try to read data from Elasticsearch to Spark using elasticsearch-hadoop, it fails with the error, which is mentioned in the first post of https://github.com/elastic/elasticsearch-hadoop/issues/853.

"Regardless of your mapping" - again, this is not my mapping, this is your Elastic ECS mapping, which is used in ECS, metricbeat, filebeat, etc.

It is simply not possible to read any data from Elastic Security / ECS via elasticsearch-hadoop library in Spark!

**Comment by massynas** [comment]
+1

**Comment by jbaiera** [comment]
I wanted to circle back to this. Thanks for voicing your feedback @asapegin, I empathize with you on this and took some time to try and track down if there was a clear location to fix this outside of the ES-Hadoop project. What resulted was a lot of chasing dead ends and finding that this pattern is not just widespread in its usage, it's expanding across different integrations. With that in mind I've reopened #853, but I don't know exactly when we'll get to solving it. The issue is quite hairy when you get into the corner cases (especially read-update-write workflows).
