### ISSUE TITLE
`More Like This` (MLT) query result is not sorted by the score

### ISSUE THREAD

**Issue by caionobrega** [elastic/elasticsearch-hadoop#1971]
### What kind an issue is this?
Probably a bug.

### Issue description

I'm trying to run the 'More Like This' (MLT) query using the apache spark connector.
The problem is that the result is not sorted by the computed MLT score. 

I think it is related to the `sort=_doc` parameter added in the [search query builder](https://github.com/elastic/elasticsearch-hadoop/blob/4a518581b7ee909f89172190ff6683c0054303d9/mr/src/main/java/org/elasticsearch/hadoop/rest/SearchRequestBuilder.java#L206).

### Steps to reproduce

Supose the index "documents" whose mapping is: [id, text].

Code:

```
val localSpark = SparkSession
    .builder()
    .appName("test")
    .config("spark.es.nodes", "localhost")
    .config("spark.es.port", "9200")
    .config("es.mapping.id", "id")
    .config("es.write.operation", "upsert")
    .config("spark.es.nodes.wan.only", "true") 
    .config("es.scroll.size", 15)
    .master("local").getOrCreate()

val query = """{"query" : {"more_like_this": { "fields": ["text"], "like": [{"_index": "documents", "_id": "fake_id"}]}}}"""

val df = localSpark.read.format("org.elasticsearch.spark.sql").option("query", query).option("pushdown", "true").load("documents")
```

I also tried adding the `"sort":"_score"` to the query, but it is **silently ignored**.

```
val queryWithSort = """{"sort":"_score", "query" : {"more_like_this": { "fields": ["text"], "like": [{"_index": "documents", "_id": "fake_id"}]}}}"""
```

### Version Info

OS:           Ubuntu 20.04.4 LTS
JVM:  openjdk version "1.8.0_302"
Hadoop/Spark:  3.1.0 (scala: 2.12.12)
ES-Hadoop:  "elasticsearch-spark-30" % "8.2.2"
ES:  8.1.3

**Comment by jbaiera** [comment]
The code that reads the query data that is passed in by users discards all but the "query" portion. This is an ergonomics feature so that we don't fail in situations where users add the unneeded "query" field at the root, but really only the query should be specified in the `query` parameter. Maybe it's not the best that it's silently ignoring the other parts, perhaps there should be a warning message or we should eschew the leniency?

Sorting, however, is a bit of a snaggy subject with ES-Hadoop/Spark. The problem is that Spark should normally read data from Elasticsearch in parallel which means that total order cannot be preserved. In that regard we set the sort order to `_doc` in the client calls. We could expose the score field as part of the metadata, but I question the usefulness of this feature for Spark. It might be reasonable to get the top X results based on score, but the regular Elasticsearch client can already do that. Sorting the data on Spark will sort the data within a partition, but partitions are not inherently ordered (that I'm aware of). You could condense the data set down to one partition so that the data is in one place and totally ordered, but if your data fits in memory, I question the usefulness of Spark for the problem at hand.

It would be great if you could share what kind of goals you are trying to achieve with sorting results in this manner within Spark. That would help guide us one way or the other on adding something that might help you out.

**Comment by masseyke** [comment]
Oh I see what you're saying (I had missed this before and am just reiterating what you said to emphasize it) -- while we could change es-spark to create a scroll with a sort field that is not `_doc`, the problem is that es-spark is actually running one scroll per spark partition and there is no guarantee about the order the partitions come back in. So sorting would have to be done spark-side, globally across partitions.

**Comment by caionobrega** [comment]
> only the query should be specified in the query parameter. 

makes sense. No changes needed then.

> get the top X results based on score, but the regular Elasticsearch client can already do that.

I see. My idea was to use ES-Hadoop/Spark only to load data and make queries. 
However, as you said, the top-n MLT use case is not suitable for this client.

Thanks for your response.
Feel free to close this issue.
