### ISSUE TITLE
Add integration with Apache Crunch

### ISSUE THREAD

**Issue by tzolov** [elastic/elasticsearch-hadoop#20]
Apache Crunch (http://crunch.apache.org/) is a framework for writing, testing, and running MapReduce pipelines composed of many user-defined functions.

**Comment by jbaiera** [comment]
Backlog Fairy Visit: Took a cursory glance at Crunch today. Latest version was released over a year ago and is 0.15. Packaged with CDH 5 at version 0.11. Only 17 commits in the last year, which makes me think that it's slowing down as a project. Since the cost for building and supporting a new integration is high, it's unlikely that we will get around to making a Crunch integration any time soon. If there is enough push from the community we can look into it, but until then, I am closing this issue.
