### ISSUE TITLE
Repository-hdfs plugin not always closing tcp connexions

### ISSUE THREAD

**Issue by jubagarie** [elastic/elasticsearch-hadoop#220]
I'm using the "repository-hdfs" plugin to store snapshots on HDFS with Elasticsearch 1.1.1. It seems that Elasticsearch doesn't properly close the TCP connections after a snapshot is created.

The result for me was a "too many open files" errors in the Elasticsearch logs. Using the "lsof" command I found a pile of more than 50k TCP connections in the CLOSE_WAIT state and as many  file descriptors.

**Comment by bflad** [comment]
Hmmm. As a point of reference, Elasticsearch 1.1.1 + CDH 5.2.1 (Hadoop 2.5.x) here, and I don't see any `CLOSE_WAIT` connections in lsof after taking HDFS snapshots.

Aside: is there a recommended way to setup the light plugin with Hadoop jars (like CDH) for startup? Is ES_CLASSPATH the way to go? Might be worth a mention in the documentation, especially since on CentOS/RHEL provided files, its not obvious since the variable not in the sysconfig file or init script. Found it in the Elasticsearch shell script itself.

**Comment by bflad** [comment]
Oh wait, totally lying, the connections were on the master nodes:
```
java      13452 elasticsearch  211u     IPv6            7964297      0t0        TCP esmaster01.example.com:58187->cdh02.example.com:50010 (CLOSE_WAIT)
java      13452 elasticsearch  212u     IPv6            7964298      0t0        TCP esmaster01.example.com:52732->cdh03.example.com:50010 (CLOSE_WAIT)
java      13452 elasticsearch  213u     IPv6            7964299      0t0        TCP esmaster01.example.com:57888->cdh01.example.com:50010 (CLOSE_WAIT)
```

So yes, still an issue!

**Comment by costin** [comment]
@bflad Sorry to heart that. 
As for the classpath, `ES_CLASSPATH` definitely works. I'll update the readme to make this clearer.

**Comment by costin** [comment]
@bflad @jubagarie you might want to try 2.1.0.rc1 since it improves the creation and closing of the `FileSystem`.

**Comment by costin** [comment]
As there hasn't been any update, I'm closing the issue.
