### ISSUE TITLE
Feature:  HBase Coprocessor -> Elasticsearch

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-hadoop#225]
This is an enhancement request to include HBase in our es-hadoop offering.

**Comment by Habam** [comment]
+1. Any updates?

**Comment by sathish-hike** [comment]
+1

**Comment by jbaiera** [comment]
It's unclear what this exactly would entail. Are we thinking that this should be for enriching data that is being returned or for HBase to become a client proxy for Elasticsearch? HBase is a fairly powerful technology, but at the same time, can have its stability drastically compromised by use of coprocessors.

Since this is a fairly open ended request, and the development cost of building and maintaining a quality coprocessor is extremely high, I am closing this issue as it is unlikely that we will be getting to it any time soon. That said, if there is enough push from the community to support this kind of integration, then we may look into re-opening or further consideration of the request. Place your +1's on the original topic post.
