### ISSUE TITLE
Provide MetricsConsumer for storing storm metrics with ES

### ISSUE THREAD

**Issue by jnioche** [elastic/elasticsearch-hadoop#325]
ElasticSearch could be used to store metrics coming from Storm and they could be displayed with Kibana later on. What about providing a MetricsConsumer for doing this? Any reason why storing metrics in ES would be a bad idea?

**Comment by jnioche** [comment]
Just in case anyone else likes the idea of indexing storm metrics with ES, I have written a [MetricsConsumer](https://github.com/DigitalPebble/storm-crawler/blob/master/external/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/metrics/MetricsConsumer.java) as part of storm-crawler.

**Comment by jbaiera** [comment]
This is a really cool idea for a feature suite. That said, most of these metrics collection frameworks provide an out of the box file format ([storm's implementation](https://github.com/apache/storm/blob/v1.2.1/storm-core/src/jvm/org/apache/storm/metric/LoggingMetricsConsumer.java)). It might be far easier to support this kind of metrics collection using a filebeat or other log tailing tool, most of which have rich sets of log prospecting features that might be better suited for use than a new collector. Additionally, since an external tailing tool would not be running inside of the storm process, it would have minimal impact on the integrity of the JVM that storm is running in. Finally, if you are using Elasticsearch in some capacity for metrics tracking, you will probably want a large set of metrics from other places like system health, uptime, network usage, etc...

All in all, feels like a great idea, but in practice there are other options available that will probably scale better, and because of this, we will probably not get around to reinventing the wheel here.
