### ISSUE TITLE
Presto Connector

### ISSUE THREAD

**Issue by aniketbhatnagar** [elastic/elasticsearch-hadoop#379]
It would be great to have a presto connector for elasticsearch that implements filter push downs properly.

**Comment by trieck** [comment]
I am not sure what would be required to enable Presto to search HIVE tables that are stored by EsStorageHandler.  Does anyone have an idea of what might be needed to enable this to work?

**Comment by aniketbhatnagar** [comment]
My opinion is that ES should have presto connector instead of making this work through HIVE. This ways, presto connector will be able to take advantage of filter push downs and translate them into ES queries.

**Comment by sumanth232** [comment]
As we know that JOIN operation is not possible in ElasticSearch among indices, Can it be achieved, i.e. can we do a JOIN operation using Presto Connector for Elastic Search ?

**Comment by haitaoyao** [comment]
Is there anybody working on this? I think it's interesting.
Here's my thoughts on the implementation:
* generate table definitions according to elasticsearch mappings
* execute query through es api with filter and push downs and transform the json response from es to presto data for further processing

**Comment by haitaoyao** [comment]
Oh, somebody is already working on it: https://github.com/facebook/presto/issues/3057
code submitted but no further response from the author.....

**Comment by rohanarora0921** [comment]
@haitaoyao @aniketbhatnagar Do you know if anyone is still working on this? Any prototype/leads would be helpful!

**Comment by synhershko** [comment]
I'm going to take this one - will probably work best as an Elasticsearch connector for Presto and then es-hadoop to support that. I'll start working this week and report as soon as I have something viable to show.

**Comment by jbaiera** [comment]
It's unlikely that we will be supporting a Presto integration any time soon. I fear that leaving this open will give a false sense of hope that we are working on it; We are not, and don't really have it on our plan for the project right now. Writing and supporting new integrations is a costly endeavor. We are happy to work with anyone who might have something put together, but it would be a long process to have a whole integration accepted via PR (good testing and full documentation are a requirement). That said, there seems to be a healthy desire for this to be made, so if there's a large enough push from the community for this kind of feature, we can reopen this and reconsider our priorities. Please put your +1's on the first post in this topic so that it is easier to follow.
