### ISSUE TITLE
Keep date formatting behavior aligned with ES API for spark serialization

### ISSUE THREAD

**Issue by mgreene** [elastic/elasticsearch-hadoop#397]
I've noticed that when streaming documents into spark with fields that have type `date`, the format that is passed to the spark job itself is that of the `java.util.Date` default. This occurs even if the underlying document has UTC millis as its format. The problem we encountered is when we reindex our data, we stream in one format, and write out a different one.

I tracked this behavior down to this serializer: https://github.com/elastic/elasticsearch-hadoop/blob/master/spark/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueReader.scala#L100-L101

I bring this up because I think this is more than a implementation preference. The ES API itself returns the format in which it was indexed with so I think that's justification for making sure the serializer behaves the same way.

The behavior in the spark connector also differs from that of the hadoop implementation, which is aligned with how the REST API behaves.

**Comment by costin** [comment]
So if I understand correctly, the issue in your case is the fact that you would like the date (which can be only represented as either a `long` or a `String`) in a primitive form instead of a `Date`, correct?

> I tracked this behavior down to this serializer

That's actually the deserializer as it reads the data from the wire.

> The behavior in the spark connector also differs from that of the hadoop implementation, which is aligned with how the REST API behaves.

There is no `Date` representation in Hadoop and thus the data is represented as a `long`. Where it does exist (Pig, Hive, Spark) the rich types are used instead. I can see though that more control over how a `Date` is represented would be convenient and having an option to enable/disable the rich object mapping would be helpful.

**Comment by costin** [comment]
Raised #422

**Comment by mgreene** [comment]
@costin Correct, I'd like to read back the same format in which it was written. From my observations, this seems to be the behavior of the REST API.

My point w/r/t the Hadoop implementation is that when considering the ES REST API, Hadoop, and Spark implementations, they all produce different views of that data type by default. Consistency would certainly be a desirable milestone here, with the preference being to copy the behavior from the API.

**Comment by costin** [comment]
Closing the issue; if the problem persists please create a new one.
