### ISSUE TITLE
Add Spark write RDD example

### ISSUE THREAD

**Issue by gquintana** [elastic/elasticsearch-hadoop#453]
There isn't any write example in Spark support documentation showing how to use `saveAsNewAPIHadoopDataset` and `saveAsHadoopDataset`.

Example of `saveAsHadoopDataset` in Java:
```
        JobConf jobConf = new JobConf();
        jobConf.set(ES_NODES, "localhost:9200");
        jobConf.set(ES_RESOURCE, "requests/simple");
        jobConf.setOutputFormat(EsOutputFormat.class);
        jobConf.setMapOutputValueClass(MapWritable.class);
        jobConf.setMapOutputKeyClass(Text.class);
        requests.mapToPair(req -> {
                    String id = req.getId();
                    Map<String, Object> document = new HashMap<>();
                    document.put("title", req.getTitle());
                    document.put("path", req.getPath());
                    document.put("duration", req.getDuration());
                    return new Tuple2<>(id, EsJavaUtils.toWritable(document));
                })
                .saveAsHadoopDataset(jobConf);
```

**Comment by costin** [comment]
@gquintana Using Elasticsearch with Spark through the M/R layer isn't the easiest or the best way out there. One needs to handle the conversion to/from `Writable`s plus the configuration is somewhat error prone.
Using the native integration is significantly easier - for example one doesn't have to use a `EsJavaUtils`...
I appreciate the example but I'm afraid it will complicate the docs more instead of making things easier. Plus there's nothing really new for this type of setup - it relies on the Hadoop configuration object which is detailed in the docs.

Cheers

**Comment by gquintana** [comment]
I agree that Hadoop stuff is verbose. But is there a simpler to write a RDD into Elasticsearch? What do you call "native integration"?

**Comment by gquintana** [comment]
I'have just stumbled upon the JavaEsSpark class which is the missing piece. This is probably what needs to documentation.

**Comment by costin** [comment]
Have you looked at https://www.elastic.co/guide/en/elasticsearch/hadoop/2.1.Beta/spark.html  ?

**Comment by gquintana** [comment]
Nope. This exactly what I was looking for.
