### ISSUE TITLE
Issue With Elasticsearch Hadoop Config, Please help me

### ISSUE THREAD

**Issue by itsprakashs** [elastic/elasticsearch-hadoop#474]
hadoop : 2.6.0
Hive : apache-hive-1.2.0-bin
Elasticsearch : 1.4.4

PATH enabled with variable HIVE_AUX_JARS_PATH also with hive-site.xml / hive-env.sh.

Jars : elasticsearch-hadoop-2.1.0.BUILD-20150604.023552-423.jar / elasticsearch-hadoop-1.3.0.M2.jar / elasticsearch-hadoop-1.3.0.M3.zip / elasticsearch-hadoop-2.0.2.jar /elasticsearch-hadoop-2.0.2.zip

Tried with all the available options but still getting the following error. Please help me.

hive> CREATE EXTERNAL TABLE wikitable (
    >     title string,
    >     redirect_page string )
    > STORED BY 'org.elasticsearch.hadoop.hive.ESStorageHandler'
    > TBLPROPERTIES('es.resource' = 'wikipedia_river/page/_search?q=*',
    >               'es.host' = 'MongoDB-1.tcgsoftwareinc.com',
    >               'es.port' = '9200');
FAILED: SemanticException Cannot find class 'org.elasticsearch.hadoop.hive.ESStorageHandler'

**Comment by costin** [comment]
For questions use the public forum, not the issue tracker since this is not a bug.
Also I recommend reading on the docs - there is no `ESStorageHandler` - that's an old class in 1.3, one should use `EsStorageHandler`.
Also adding multiple versions of the library to the classpath (1.3.0.M2, M3, 2.0.2) doesn't make sense - you should use only one version.
Otherwise, the runtime will pick an arbitrary version and chaos will ensue.

This is the third time you are politely redirected to the public forum and again you chose to ignore it; there won't be any further updates / answers from my side in the future.

**Comment by itsprakashs** [comment]
Really Sorry....I will find out the public forum...
