### ISSUE TITLE
esPort not been read

### ISSUE THREAD

**Issue by emmekappa** [elastic/elasticsearch-hadoop#481]
I just notice that although I specified both

    es.nodes property = "myhost:10160" 

and 

    val options = Map("pushdown" -> "true", "path" -> "foo/bar", "nodes" -> "myhost", "esPort" -> "10160")

My worker says 

    ERROR NetworkClient: Node [Connection timed out] failed (myhost:*9200*); no other nodes left - aborting...

I'm using the latest snapshot.

Any help?

**Comment by emmekappa** [comment]
I'm using Spark 1.3.1

**Comment by costin** [comment]
@emmekappa Thanks for reporting. On closer diagnostics it looks like the camel-case style is simply not effective as the options are lower-cased by Spark before reaching the connector... Ironically enough the tests contained a camelcase variable but that was applied before hand and thus its presence in SQL didn't actually have any effect.

Long story short, when using the +Map+ variant one is not restricted in syntax so specify the properties by their full name:
```scala
val options = Map("es.nodes" -> "myHost", "es.port" -> "10160")
```
Note that `path` is really an alias for "es.resource"; further more you don't need to specify it since it's already declared through the `load` or `read` method (it's the path from where the resource is loaded in the end).

Also `pushdown` is by default true so again, no need to specify it.

**Comment by costin** [comment]
Closing the issue as the docs have been updated.
