### ISSUE TITLE
Hive queries are running very slow with where clause

### ISSUE THREAD

**Issue by ashubhumca** [elastic/elasticsearch-hadoop#527]
Hi,

I'm using **elasticsearch version 1.2.1 and hadoop-2**
This jar is used for the communication: elasticsearch-hadoop-2.1.1.BUILD-SNAPSHOT.jar

Issue: 

For query: *"select session_id from app_sessions_prod where 1=1 limit 5;"* I'm getting the result in 15 seconds but when I'm using any where clause (including table columns) e.g *"select session_id from app_sessions_prod where 1=1 and session_id = '8043472_2015-05-07 06:55:24' limit 5;"* then it is running very slow. Even after running it for hours, it is not completing.

Please help me.

Could you tell me if these where cluases applied on ES itself before getting the data into Hive for further processing? For any given query, what part will execute on ES??

Thanks in advance,

Ashish

**Comment by costin** [comment]
Hive doesn't support push-down operations for custom stores. If you turn on logging and look at your job, most likely you'll see Hive asking all the data from Elasticsearch in order to do the filtering by itself.
With limit 5, one would argue, it could be smarter than this but again, it depends on the version and the path taken by the planner.

As an alternative, you could look at SparkSQL which does allow the connector to push down its operations; in fact all SparkSQL is translated into a QueryDSL at runtime.

**Comment by ashubhumca** [comment]
Thanks for the reply Costin.

I'm just thinking if we can have push-down functionality in the API. Do you have any plan for that? If yes, then I would like to contribute for that feature.

**Comment by costin** [comment]
The plan has been there for a long time - unfortunately this needs to be fixed in Hive, to expose the proper hooks for external storages (like us) to plug into. Where they are available (like SparkSQL) such functionality is already available.

In other words, unless Hive exposes the proper API/hooks, there's not much we can do.

**Comment by costin** [comment]
Closing the issue as there's not anything else we can do. At least at the moment.
