### ISSUE TITLE
Spark not able to find ES server on AWS

### ISSUE THREAD

**Issue by mborkar** [elastic/elasticsearch-hadoop#550]
I am using ES with spark 1.4.1 and hope to write data to ES using spark. But now I am using AWS. I have VPC instance and have spun spark cluster. The same code worked for me on my local but when I use it on AWS it doesn't write to ES node and neither it complains. Probably just ignores. I guess it is not able to locate ES node?

```scala
package scalaProject

import org.apache.spark.SparkContext
import org.apache.spark.SparkConf
import org.apache.spark.sql.SQLContext   
import org.apache.spark.sql.SQLContext._
import org.apache.spark.sql.functions._
import org.elasticsearch.spark.sql._

object DFload {

// case class used to define the DataFrame
case class Person(name: String, age: Int)

  def main(args: Array[String]) {
    val conf = new SparkConf().setAppName("LD").setMaster("spark://localhost:7077")
    conf.set("es.index.auto.create", "true")
    val sc = new SparkContext(conf)
    val sqlContext = new org.apache.spark.sql.SQLContext(sc)
    // required for 1.3+ data frames
    import sqlContext.implicits._


//  create DataFrame
val people = sc.textFile("/opt/spark-1.2.1-bin-hadoop2.4/examples/src/main/resources/people.txt")   
        .map(_.split(","))
        .map(p => Person(p(0), p(1).trim.toInt))
        .toDF()

people.printSchema()
people.select("name").show()
people.saveToEs("spark/people")
}
}
```

**Comment by costin** [comment]
_edited your post to add minor formatting - please do so in the future_

First off, when running in AWS you need to take into account the private vs public IPs of your nodes. This is a common issue is documented and has been explained at length. 

Further more your code has some peculiar items in it:
- you are referring to `localhost` - this shouldn't be the case with AWS typically
- you are trying to load spark 1.2.1
- your code comments and imports indicate 1.3.1

There's no such thing as ignoring - either the operation successeds or it fails (in which case one gets an error). Since you are not specifying the ES location, likely it is going to `localhost` - again something not used with AWS.

All in all, it looks like you are not properly monitoring the correct code/data source.

**Comment by costin** [comment]
duplicated by #566 #565 #577
