### ISSUE TITLE
read huge data from es speculation 

### ISSUE THREAD

**Issue by zqhxuyuan** [elastic/elasticsearch-hadoop#552]
our es type is a big map like this:  
```
{
  "map1": {
    key1: val1
  },
  "map2": {
    key: value
  },
  "key3" : "...."
}
``` 
and hdfs/hive table split this big map to multi map:  
```
key3: string
map1: map<string,string>
map2: map<string,string>
```
so after esRDD, we **has a parsing method make origin es big map to another map**.  
with returned parsedRdd, we do like this
```
parsedRdd.map(rdd=>{
   ...
   (key3, map1, map2, map3....)
}).toDF.write.parquet("hdfs....")
```

But parsing method seems take a lot of time. I tested by doing parsedRDD.count  
when records about 50 milliin, cost 5 minute. our data of one day has nearly 2000 millin, may cost 200 min=4hour  
when I run on spark-submit(use one day data by query json to esRDD). something strange happen
```
Application ID	Name	Cores	Memory per Node	Submitted Time	User	State	Duration
app-20150924162635-0144 (kill)	ES2HDFS	0	4.0 GB	2015/09/24 16:26:35	admin	WAITING	54 s
app-20150924162627-0143 (kill)	ES2HDFS	0	4.0 GB	2015/09/24 16:26:27	admin	WAITING	1.0 min
app-20150924162627-0142 (kill)	ES2HDFS	180	4.0 GB	2015/09/24 16:26:27	admin	RUNNING	1.0 min
app-20150924162559-0141 (kill)	ES2HDFS	30	4.0 GB	2015/09/24 16:25:59	qihuang.zheng	RUNNING	1.5 min
```
there are more then 1 application executed. even I change spark.speculation=false, which is the default value.  and background log indicate that the 14/17 task was stucked.  

actualy there are some other strange problem I occur.
1.I do pass --master with spark-submit cmd, but app failed with : A master URL must be set in your configuration.  so I have to mannualy set master and some other options in my code.
I guess data is too large make some other task failed.  

update:
after I manualy killed all application only left the last one. but some times later, it auto restart(notice the submit time of app).

```
Running Applications

Application ID	Name	Cores	Memory per Node	Submitted Time	User	State	Duration
app-20150925062857-0151 (kill)	ES2HDFS	0	4.0 GB	2015/09/25 06:28:57	admin	WAITING	3.5 h
app-20150925045755-0150 (kill)	ES2HDFS	0	4.0 GB	2015/09/25 04:57:55	admin	WAITING	5.0 h
app-20150925030731-0149 (kill)	ES2HDFS	245	4.0 GB	2015/09/25 03:07:31	admin	RUNNING	6.8 h
app-20150924162559-0141 (kill)	ES2HDFS	30	4.0 GB	2015/09/24 16:25:59	qihuang.zheng	RUNNING	17.5 h
```

**Comment by zqhxuyuan** [comment]
I guess there are less tasks, so that make application too slow. Do I Have any option to set task numbers to esRDD method?  As I Know from <https://www.elastic.co/guide/en/elasticsearch/hadoop/current/arch.html> :  task number is decided by shards in es index.  If I did't change es shards, are there anyway to do this?

**Comment by costin** [comment]
@zqhxuyuan this is probably better suited for the [forum](discuss.elastic.co) vs the issue tracker.
If I understand correctly your issue is that your Spark jobs are quite slow and you are not sure why.
Parallelism might be an issue - currently we don't allow in the API (yet) a way to increase parallelism beyond that of a shard.
You could further divide an `RDD` in Spark directly, for example: 
`sc.esJsonRDD(cfg).mapPartitionsWithIndex(writeIterInBatches).count()`

However all the above assumes that the issue lies with the number of documents returned by the connector which is too high for a task. Which might or might _not_ be the case here especially considering the amount of custom code and IO that it involves (such as computing and writing parquet files to disk).

**Comment by zqhxuyuan** [comment]
tks, as large data in es, we choose split one day data to 48 half hours  to query instead one whole day.
