### ISSUE TITLE
Support for null-safe equality comparison at Spark-Elasticsearch datasource.

### ISSUE THREAD

**Issue by HyukjinKwon** [elastic/elasticsearch-hadoop#569]
For Spark 1.5, `EqualNullSafe` can be pushed down as a filter operator.
(https://issues.apache.org/jira/browse/SPARK-9814)

I think this can be easily done adding combination of equality comparison query and `missing` filter adding a `case` at `ElasticsearchRelation.translateFilter()` in `org.elasticsearch.spark.sql.DefaultSource.scala`

Could I open a PR for this?

**Comment by costin** [comment]
I missed the new filter. Sure, go ahead with a PR (take a look at `StringStartsWith` and co to add the case in a backwards compatible way with Spark versions lower than 1.5).

Thanks,

**Comment by costin** [comment]
Hi,
Thanks for the PR. It is merged in master and 2.x
I've added a null check for `EqualsTo` - for `NullSafeEquals` it doesn't seem to make sense considering nulls are handled by the operator directly (based on what I've seen in the Spark code).
The same seems to apply for String operators - in fact is null is passed, the whole filter can't really work properly since the regex becomes global (every string starts or ends with null for example).

Cheers,

**Comment by HyukjinKwon** [comment]
Yeap I agree. I think this wouldn't be a big deal.
Thanks :)
