### ISSUE TITLE
Hive table with ES storage lose column comments

### ISSUE THREAD

**Issue by vanjor** [elastic/elasticsearch-hadoop#587]
when create a hive table by ES storage, the comment for each column is lost, that is when re-query the table schema, the comments by each column is missed. Wonder is there  anyway to support storage the comment? 

e.g. hive scripts:

``` sql
drop table online.user_gps_record_es;
CREATE EXTERNAL TABLE IF NOT EXISTS online.user_gps_record_es (
  user_id STRING COMMENT 'user id',
  active_time STRING COMMENT 'user spot time',
  longitude DOUBLE COMMENT 'longitude',
  latitude DOUBLE COMMENT 'latitude',
  app_type STRING COMMENT 'user app type',
  pdate STRING COMMENT 'pdate'
)
COMMENT 'user gps history, [ES:resys_user_gps_db/user_gps_record]'
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'resys_user_gps_db/user_gps_record','es.nodes'= 'es.xxx.com',
              'es.port'= '9200','es.mapping.id' = 'id','es.index.auto.create' = 'true',
              'es.batch.size.entries' = '1000','es.batch.write.retry.count' = '10000','es.batch.write.retry.wait' = '10',
              'es.batch.write.refresh' = 'false','es.nodes.discovery' = 'true','es.nodes.client.only' = 'false'
             );
```

**Comment by costin** [comment]
This is a side-effect due to the way Hive saves/serializes comments in a table - typically through the `0` character which caused the serialized Hive job configuration to be invalid. In an effort to prevent this from happening (see #322 and #359) (note this is Hive specific, it has nothing to do with ES), the connector removed these lines which might explain why the comments are stripped as well.
You can modify this behaviour which is enabled by default by setting
`es.hive.disable.columns.comments.fix` to true in your ES-Hadoop configuration.

For more information about the problem, see this [main Hive issue](https://issues.apache.org/jira/browse/HIVE-8307).

Hope this helps,

**Comment by jbaiera** [comment]
Closing this out as there doesn't seem to be anything actionable.
