### ISSUE TITLE
Not specifying containers throws Exception

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#598]
```
15/10/28 15:12:19 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm2
Abnormal execution:/ by zero
java.lang.ArithmeticException: / by zero
at org.elasticsearch.hadoop.yarn.util.YarnUtils.yarnAcceptableMin(YarnUtils.java:113)
at org.elasticsearch.hadoop.yarn.util.YarnUtils.minMemory(YarnUtils.java:103)
at org.elasticsearch.hadoop.yarn.compat.YarnCompat.resource(YarnCompat.java:71)
```
This happens as well when I omit the containers=12 parameter

More about it [here](https://discuss.elastic.co/t/hadoop-jar-elasticsearch-yarn-2-1-1-jar-start-throws-arithmeticexception-by-zero/33300).

**Comment by WalterDalton** [comment]
Is there any work around on this?  I can't even really see with what is causing this.

**Comment by WalterDalton** [comment]
I believe the issue comes into play when I am using fine-grain scaling running Yarn on the Myriad project. For Fine Grain scaling, we set a property "yarn.scheduler.minimum-allocation-vcores" to be 0.  Where that comes into play is that in 

https://github.com/elastic/elasticsearch-hadoop/blob/master/yarn/src/main/java/org/elasticsearch/hadoop/yarn/util/YarnUtils.java

On Line 107 we have:

 private static int yarnAcceptableMin(Configuration cfg, String property, int value) {
        int acceptedVal = Integer.parseInt(cfg.get(property));
        if (acceptedVal >= value) {
            return acceptedVal;
        }

        if (value % acceptedVal != 0) {
            return acceptedVal * Math.round(value / acceptedVal);
        }
        return value;
    }

Where I believe the value that I set to 0 ends up being in the acceptedVal variable, causing a divide by 0. Thus, I believe we should update the es-yarn code to check if that value is 0 and then know that we are above the the accepted value if we are > 0 rather then doing a divide operation here. This value CAN be 0, and thus we shouldn't divide by 0.   

(I  can read Java, but I am not a programmer, so I am hesitant to write code to fix it...) 

The good news is for this, we should be able to work around by setting the value to something >0 in the short term, but longer term we should address this.
