### ISSUE TITLE
Batch SaveToES with foreachpartition

### ISSUE THREAD

**Issue by yukti-kaura** [elastic/elasticsearch-hadoop#599]
Hi 

I have a data JAVARDD which needs to be written to ES
It has 32 partitions
However the write to ES is sequential using saveToES
I do not care for the order of insert
Is there a possibility to write from foreachPartition or write parallely?

Thanks,
Yukti

**Comment by costin** [comment]
How many cpu cores do you have available for Spark? If your RDD has 32 partitions operations on it, including `saveToEs` should be distributed/parallelized automatically without any additional work.

**Comment by yukti** [comment]
The execution is sequential, for each partition
Logs indicate all the partitions, being processed in sequence
1
2
...
32

Also, read somewhere that if we use Singletons like JavaEsSpark etc.. they
cannot be sent to the workers and hence create a bottleneck.

Kindly guide and suggest

On Tue, Nov 10, 2015 at 1:42 AM, Costin Leau <notifications@github.com>
wrote:

> How many cpu cores do you have available for Spark? If your RDD has 32
> partitions operations on it, including saveToEs should be
> distributed/parallelized automatically without any additional work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-hadoop/issues/599#issuecomment-155177655>
> .
>



-- 
Warm Regards,
Yukti Kaura

**Comment by AlexeyRaga** [comment]
Same problems here.

The job is very simple:

    val data       = sqlContext.load(params.srcPath)
    data
      .map(r => toModel(r))
      .map(m => transform(m))
      .saveToEs("{index:'partitioned_index_'yyyy-MM}/document")

And no matter how big is the cluster and how I set up spark (# of executors, memory, etc) the insert process seems to be sequential, no parallelism at all.

**Comment by yukti** [comment]
Hi Alexey will suggest to use the Elasticsearch bulk API over this one.
That is significantly faster.


Open and close connections in ForeachPartition , ensure that your bulk size
is optimum.

On Mon, Nov 16, 2015 at 5:07 AM, Alexey Raga <notifications@github.com>
wrote:

> Same problems here.
>
> The job is very simple:
>
> val data       = sqlContext.load(params.srcPath)
> data
>   .map(r => toModel(r))
>   .map(m => transform(m))
>   .saveToEs("{index:'partitioned_index_'yyyy-MM}/document")
>
> And no matter how big is the cluster and how I set up spark (# of
> executors, memory, etc) the insert process seems to be sequential, no
> parallelism at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-hadoop/issues/599#issuecomment-156870242>
> .
>



-- 
Warm Regards,
Yukti Kaura

**Comment by costin** [comment]
I'll investigate; currently I don't have any ideas why this occurs. ES-Hadoop doesn't handle the partitions directly instead it is Spark through its DAG Scheduler that decides who and when to run (in this case the ES-Hadoop `save`).
Note that even if there are multiple partitions, unless there are available Spark nodes/CPU, they do get executed in sequence since there's only one CPU.

@yukti Sure, one could use the bulk/transport API directly but that's not as convenient as ES-Hadoop. Does that solve parallelism for you? The Java client relies on async operations but these are internal to it not Spark...

Personally I'd like to see what's the issue in your case and improve the situation - it will be a win-win situation.

**Comment by yukti** [comment]
Hi Costin,

ES-Hadoop is more convenient when RDD is in picture.
However, incase it is an Iterable which is involved, Bulk API comes in
handy, more so since I have fine grain control over its configuration.


Within ForeachPartition of Spark there is an Iterable of records, however,
even contrary to my belief ForeachPartition too runs sequentially , so
incase there are 32 partitions each partition runs one after the other

I am using ForeachPartitionAsync.

HOwever, this sequencing is faster than the EsSpark API.

Not sure why that is the case.

Thanks,
Yukti.


On Mon, Nov 16, 2015 at 8:59 AM, Costin Leau <notifications@github.com>
wrote:

> I'll investigate; currently I don't have any ideas why this occurs.
> ES-Hadoop doesn't handle the partitions directly instead it is Spark
> through its DAG Scheduler that decides who and when to run (in this case
> the ES-Hadoop save).
> Note that even if there are multiple partitions, unless there are
> available Spark nodes/CPU, they do get executed in sequence since there's
> only one CPU.
>
> @yukti <https://github.com/yukti> Sure, one could use the bulk/transport
> API directly but that's not as convenient as ES-Hadoop. Does that solve
> parallelism for you? The Java client relies on async operations but these
> are internal to it not Spark...
>
> Personally I'd like to see what's the issue in your case and improve the
> situation - it will be a win-win situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-hadoop/issues/599#issuecomment-156904121>
> .
>



-- 
Warm Regards,
Yukti Kaura

**Comment by costin** [comment]
Both `foreach` and `foreachPartition` are run across the cluster when possible - that's the whole premise behind using the `RDD` in the first place.

If you look at the source, you'll notice the two methods are actually quite similar:
```scala
  // Actions (launch a job to return a value to the user program)

  /**
   * Applies a function f to all elements of this RDD.
   */
  def foreach(f: T => Unit): Unit = withScope {
    val cleanF = sc.clean(f)
    sc.runJob(this, (iter: Iterator[T]) => iter.foreach(cleanF))
  }

  /**
   * Applies a function f to each partition of this RDD.
   */
  def foreachPartition(f: Iterator[T] => Unit): Unit = withScope {
    val cleanF = sc.clean(f)
    sc.runJob(this, (iter: Iterator[T]) => cleanF(iter))
  }
```
Again, if you have doubts about what is going on, the Spark reference docs has a whole section on how to monitor partitioning and track down execution. Potentially you can try Databricks's cloud and see whether that changes your behavior.

As for the `async` version things are exactly the same however in this case your code is not waiting/blocking for the response - the work simply happens in the background.
Async rarely makes things faster for the call per se, rather it decouples the caller from the actual work so it can pursue other interests - that doesn't mean though the work has been down.
You can check this for yourself by calling `get` on the `FutureAction` which basically translates the async usage into a sync one.

**Comment by rubenjgarcia** [comment]
I have a similar problem. I'm using this library and it works great but when I use in production we have a problem

Our dataset need 974 partitions because has more than 400 million of lines. We use 16 nodes, and we use this configuration for ESSpark

```
.set(ConfigurationOptions.ES_BATCH_SIZE_BYTES, "10mb")
.set(ConfigurationOptions.ES_BATCH_SIZE_ENTRIES, "50000")
.set(ConfigurationOptions.ES_BATCH_WRITE_RETRY_WAIT, "5s")
```

With saveToES it takes forever, @costin do you have any idea to decrease the data upload time?

Thanks

**Comment by cscetbon** [comment]
AFAIU those actions need to access SparkContext and everything that requires access to SparkContext is done in the driver not on workers

**Comment by mqiu2017vs** [comment]
Does this mean in order to use saveToES, only drive will do the job and the worker nodes has no use?

**Comment by mqiu2017vs** [comment]
Hi Costin
Do you have any updates on this issue?

Thanks

**Comment by jbaiera** [comment]
@mqiu2017vs The `saveToEs` method executes `runJob` on the RDD, which delegates downward into Spark's `DAGScheduler`, which handles launching the job on the Spark Cluster. Unfortunately this is an older issue and the original author has not responded in over a year. I'm going to go ahead and close this issue as it has stalled out. If an issue such as this arises again, we'll open a new ticket for it to track it.

**Comment by mqiu2017vs** [comment]
Hi James,

I think this is still an issue,  Because I use the same way to saveToES, I
can see that only the driver is doing the job sequentially so the
performance is not good.

Please open a new ticket for this.

Bests,

Min Qiu
