### ISSUE TITLE
es-hadoop hive date map to timestamp field error

### ISSUE THREAD

**Issue by arronli** [elastic/elasticsearch-hadoop#639]
1,Query data from hive:
    es mapping  field, type 'date', format 'basic_date'  , some value like '20150916'
 
    If set hive type  'timestamp'  ,then i get a wrong result value '20150916-01-01 00:00:000:00.0';

    If set hive type ‘string’ , then i get error :Failed with exception java.io.IOException:org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.hive.serde2.io.TimestampWritable cannot be cast to org.apache.hadoop.io.Text.

2,Write data from hive:
    mapping to a es field,  type 'date' format 'date_hour_minute_second'

    If set hive type  'timestamp' , get error like Caused by: java.lang.IllegalArgumentException: Invalid format: "2015-09-16T10:40:40+08:00" is malformed at "T10:40:40+08:00"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
	at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.parseStringValue(DateFieldMapper.java:360);

    If set hive type 'string', writes successfully,then back to the first question, can not read from hive.

es-hadoop version :   elasticsearch-hadoop-2.2.0.BUILD-20151228.024627-194
hive version           :   hive1.1.0 cdh5.4.8 
es version              :   es2.1

**Comment by costin** [comment]
First off, please use ES-Hadoop 2.2.0-rc1 or the latest dev build since a lot of fixes have been made since then.
The handling of the date in ES-Hadoop needs to be done through ISO 8601 (as explained [here](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/mapping.html#mapping-date)).
Looking at the your errors there are a couple of things:

1. Your data contains only the date in a format which is not ISO8601 compatible. In these cases you can disable 'rich' date mapping through `es.mapping.rich.date` property as explained [here]

2. Again, your date needs to be in ISO8601 format otherwise it is not accepted. It looks like it is however your field does not seem to be configured to accept this format (explained again in the docs).

Cheers,

**Comment by arronli** [comment]
@costin  thx so much!
