### ISSUE TITLE
Error when opening project with IntelliJ

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch-hadoop#686]
I get this after a fresh clone:

<img width="948" alt="screen shot 2016-01-31 at 2 11 09 am" src="https://cloud.githubusercontent.com/assets/212252/12699331/28b14da0-c7c0-11e5-8fe9-2713e3f5c890.png">

I have both Gradle and Scala installed, so seems like some missing setting?

In case that matters, I ran `gradle build` via CLI before opening with IntelliJ to give the packages download a boost

**Comment by costin** [comment]
I'm not using IntelliJ so I'm not sure what to tell you.
Looks like it expects the project folders to be under the root source which is not mandatory - in fact, the Spark project (`sql-12` and `sql-13`) both share a common piece of code.
An alternative would be to use `gradle idea` command to generate the necessary files and use those without relying on IntelliJ IDEA integration.
I do the same with Eclipse simply because it's a lot simpler and more reliable.

**Comment by jbaiera** [comment]
Reproduced with v15. Upgrading to v16 added new features to fix the import issues.

I was able to reproduce this error using a fresh clone and Idea v15. By running the `./gradlew idea` command you can open the project in Idea (not import) but not all of the source sets are recognized and the Gradle support is not hooked up. Attempting to enable Gradle support produces the same error response. It seems that Idea v15 does not support the way we configure source roots for the spark portion of the project. After enabling the Scala plugin, I found that the version of the Gradle wrapper `(v2.12)` used in the project itself [does not gel very well with Scala projects in Idea v15 either](https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-152976)...

Idea v16 added [greater support for Gradle projects and multiple source sets by realigning their project model](https://www.jetbrains.com/idea/whatsnew/#gradle). After upgrading to Idea v16 the project correctly imports and builds both directly in Idea and through Idea's Gradle integration. The newer version of the Scala plugin for v16 seems to also have been updated to fix the Gradle intraction issues I was seeing in v15.
