### ISSUE TITLE
Different result between sc.esRDD versus EsSpark.esRDD

### ISSUE THREAD

**Issue by randallwhitman** [elastic/elasticsearch-hadoop#687]
In a certain test, I'm seeing one result with `EsSpark.esRDD` but two results with `sc.esRDD`.

Can you reproduce the following result?  (It may be that I am getting confused by instability in my development environment, though I've got the following result consistently multiple times.)

Elasticsearch-hadoop 2.2.0.BUILD-SNAPSHOT; Elasticsearch Java API 1.7.[14]; Elasticsearch server 1.6.2; Spark-1.6.0; CentOS-6.

```scala
    val rawCore = List( Map("colint" -> 1, "colstr" -> "s"),
                        Map("colint" -> null, "colstr" -> null) )
    sc.parallelize(rawCore, 1).saveToEs(coreResource, connectorConfig)
    val qjson =
      """{"query":{"range":{"colint":{"from":null,"to":"9","include_lower":true,"include_upper":true}}}}"""
```
```scala
    val rdd2 = EsSpark.esRDD(sc, coreResource, qjson, connectorConfig)
    val got = rdd2.collect().size   // 1
```
```scala
    val rdd2 = sc.esRDD(coreResource, qjson, connectorConfig)
    val got = rdd2.collect().size   // 2
```

**Comment by costin** [comment]
Something is off and based on your code you are probably running two separate tests against the same stateful ES instance, resulting in the difference.
If you look at the source, you'll notice that `SparkContext.esRDD` is a simple alias for `  def esRDD(resource: String, query: String) = EsSpark.esRDD(sc, resource, query)`.
In other words, it is the exact same method, no more, no less...
I don't know what else to tell you except you're probably doing something wrong (make sure you are refreshing Elasticsearch before the count since otherwise you might see the count before and then after the refresh and that will affect the outcome).

**Comment by randallwhitman** [comment]
Agree that is strange because the methods are aliases.
I can make a note to look into the refresh API.
