### ISSUE TITLE
Support ignoring certain write exceptions

### ISSUE THREAD

**Issue by msukmanowsky** [elastic/elasticsearch-hadoop#707]
In our production cluster, it's possible an index required for writes is closed which leads to exceptions such as:

```
An error occurred while calling z:org.apache.spark.api.python.PythonRDD.saveAsNewAPIHadoopFile.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 7.0 failed 4 times, most recent failure: Lost task 1.3 in stage 7.0 (TID 196, ip-10-21-0-41.ec2.internal): org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Forbidden(403) - [IndexClosedException[[blah] closed]]]; Bailing out..
```

Normally, we'd handle this on the Spark driver side, but the nature of our time-based indices would make our driver scripts pretty messy to handle this case.

Think it'd be handy to have a configuration parameter to control ignoring these exceptions. Suggest adding `es.write.ignore_exception` which would support a `closed` value to start, but optionally other values down the line like `missing` and `closed_or_missing`.

Happy to try and add support for this myself if people think this makes sense.

**Comment by jbaiera** [comment]
Generally ES-Hadoop takes a fail fast approach to handling errors. That being said, there has been pushing from the community to add exception suppression in cases of version conflicts. While conversations regarding version conflict error suppression are still ongoing, I do not think we should explore suppressing errors for closed indices. In this case, it may be easier and more efficient to keep track of which dates have since been closed, and filter the data out explicitly in Spark instead of loading up your bulk requests with data that will be rejected and ignored.
