### ISSUE TITLE
HTTP chunking and compression  support

### ISSUE THREAD

**Issue by eugenemiretsky** [elastic/elasticsearch-hadoop#804]
Are HTTP chunking and compression supported? 

Both of these features are very important when writing over low bandwidth, high latency network. 

A good discussion on HTTP compression in ES: https://github.com/elastic/elasticsearch/issues/7309

**Comment by jbaiera** [comment]
ES-Hadoop is built on top of Apache Commons HTTP v3.0.1 which does not support compression. Experimental support for compression was added in v4.1 and enabled by default in v4.3, but will not be backported to 3 in any capacity. Since we use the library versions that are provided with Hadoop to avoid conflicting jars and to facilitate simpler usage of the library this would need to wait until Hadoop updates their version of Commons HTTP.

HTTP chunking is available in v3.0.1 but we explicitly set it to disabled. I'm not sure I immediately see the benefit of turning it on (or adding a toggle) by itself since the data that we send across the wire is all accumulated in memory before being flushed, and we do not send data across the wire before it is done being accumulated.

**Comment by jbaiera** [comment]
Closing this out as there are no real courses of action to take.

**Comment by s4ch1n** [comment]
@jbaiera Since Http compression was critical for our project, I've added support for compressing Http Playload(Gzip) for outgoing traffic from Hadoop to ES without upgrading Http Client to 4.x, This solution won't enable compression for ES response body.  

Sharing the change, if any one interested can use this. 
 
https://github.com/s4ch1n/elasticsearch-hadoop/commit/d9327759a7f8da502e1b03789f5cab998b60c6e4 

I don't to create a PR since it's a hack.
