### ISSUE TITLE
Spark 2.0 stream interfaces

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#818]
Spark 2.x introduces continuous streaming (similar to some degree to Storm).  While for reading streaming from ES is not yet possible, writing a stream to ES is.
The hooks in Spark that we need to investigate (currently as `trait`s) are `StreamSourceProvider` and `StreamSinkProvider`. 
The latter in particular should be easy to implement,

**Comment by jbaiera** [comment]
Took some time and attempted an implementation but I've hit some snags and I'm having a hard time making any further progress. 

The `Sink` interface which does the actual data consumption is handed a `DataFrame` (called 'data') that contains the result batch. According to the `Sink` interface documentation:
> Note: You cannot apply any operators on `data` except consuming it (e.g., `collect/foreach`). Otherwise, you may get a wrong result.

After doing some very roundabout digging, I found a comment in the `ForeachSink` that contradicts this:
>This logic should've been as simple as:
```
data.as[T].foreachPartition { iter => ... }
```
Unfortunately, doing that would just break the incremental planing. The reason is,
`Dataset.foreachPartition()` would further call `Dataset.rdd()`, but `Dataset.rdd()` just
does not support `IncrementalExecution`

The `Dataset.foreach` operation follows the same call progression, and is therefor subject to the same issue. There was an [item opened up on the Spark Jira](https://issues.apache.org/jira/browse/SPARK-16264), but it's been closed as "won't fix", citing that the `Sink` trait should be modified to be closer to the `ForeachWriter` instead of exposing `DataFrame`.

If this is the case, one possibility to get something up and running would be instead of implementing a whole new Sink we could just implement a `ForeachWriter` and use it with the `ForeachSink`. I think this makes a lot more sense if the plan for `Sink` is to be pretty much the same as a `ForeachWriter`.

**Comment by koertkuipers** [comment]
i think a ForeachWriter for elasticsearch would be a great start

StreamSinkProvider doesnt feel like a stable api yet.

**Comment by jbaiera** [comment]
This has finally been added as an alpha feature for ES-Hadoop 6.0 under the 0b0f95c436d51eaeec37f0e6f9e5ccb6d33d2800 commit
