### ISSUE TITLE
Version compatibility detection wrong in elasticsearch-spark-20 5.0.0-alpha5

### ISSUE THREAD

**Issue by fpopic** [elastic/elasticsearch-hadoop#824]
- [x] Bug report

### Issue description

I tried **5.0.0-alpha5** it works with **Spark 2.0.0**, but this WARN shows:

`WARN EsSpark: Incorrect classpath detected; Elasticsearch Spark compiled for Spark 1.3 (or higher) but used with Spark 2.0.0`

### Steps to reproduce

build.sbt:

```
lazy val root = (project in file(".")).settings(
  sbtVersion := "0.13.12",
  scalaVersion := "2.11.8"
)

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.0.0",
  "org.apache.spark" %% "spark-sql" % "2.0.0",
 
  "org.elasticsearch" %% "elasticsearch-spark-20" % "5.0.0-alpha5"
)
```

### Version Info

Hadoop/Spark :  Spark 2.0.0
ES-Hadoop :  Elasticsearch Hadoop v5.0.0-alpha5 [c513369b06]
ES :  2.3.4

**Comment by jbaiera** [comment]
Thanks for opening the issue. Translating over the triaging of the bug from the last thread:

The compatibility check code assumes Spark 1.3 compatibility in the case that `EsSchemaRDDWriter` is _absent_. This class was only present in the old es-spark `1.0-1.2 compatibility` packages. Since the `1.0-1.2` packages have been removed with the advent of Spark 2.0, the check will never find that class and thus will erroneously assume that every version run is the es-spark `1.3` compatibility level.

This is not a blocker, as it simply prints a warning log, but it is indeed confusing.

**Comment by costin** [comment]
Indeed, a leftover from the 2.x version. It should be updated for Spark 2.0 (to check whether the 1.3 version is used with Spark 2.0 by accident or vice-versa). The log warning is much better than the weird class errors that one gets instead.
