### ISSUE TITLE
Spark to ES pushdown and count

### ISSUE THREAD

**Issue by chernals** [elastic/elasticsearch-hadoop#867]
I am not sure this is supported in the first place, but is a simple `count` on an index pushed down to ES?

I'm not sure what ES-query it is doing but Kibana gives a total number of 'hits' in less than 1 second while 

`sqlContext.read.format("org.elasticsearch.spark.sql").option("es.nodes", "es-1").load("index/type").count`

takes 10 minutes.

**Comment by costin** [comment]
Count can only be pushed down on an RDD - on the `DataFrame`/`Dataset` Spark perceives it as an aggregation and does not push it down.
On the `RDD` it was actually implemented some time ago but reversed since the semantics changed - folks expected `count` to _materialize_ the `RDD` which it did not.
It could be brought back as a dedicated `es` method (such as `esCount`) if there's a need. But again, this only applies at the RDD level not in SQL which is what you ask above.

**Comment by chernals** [comment]
Thanks for your quick reply. I did not know that the Data(frame|set) API was seeing it as an aggregation. Does that mean that even if we could imagine to push it down anyway that would be a change at the catalyst level and not at all at the es-hadoop level?

**Comment by jbaiera** [comment]
> Does that mean that even if we could imagine to push it down anyway that would be a change at the catalyst level and not at all at the es-hadoop level?

I'm sorry to say that it's a little more complicated than just that. Catalyst is designed and built to operate on data within Spark. Aggregations are very separated from the underlying Datasource that backs a Data(frame|set). We have yet to find way to reconcile the disconnect between catalyst's aggregation methods and the rest of the api hooks that allow us to read from Elasticsearch. On top of this, it's deceptively difficult to determine when an aggregation could be pushed down at all, especially if you count rows in Datasets/Dataframes that are read from Elasticsearch but transformed using Spark in some way before the counting.

So the answer is really "both": There would need to be significant changes in catalyst to leverage pushing down aggregations to Elasticsearch, and even if these changes were to be realized, es-hadoop would obviously have to implement whatever API hooks were provided to get the functionality.

**Comment by costin** [comment]
As @jbaiera mentioned, we need to meet in the middle. That is for Spark API to give us enough 'hooks' into its calls so that we can properly create the equivalent queryDSL.
Spark SQL supports push down but not on all operations, such as count/aggs. As such es-hadoop cannot tell whether there's a count or not involved - in fact, all it knows from Spark is that it has to read all the data...

**Comment by chernals** [comment]
Costin, James,

Thanks a lot for all the info!

On Thu, Oct 13, 2016 at 09:46 Costin Leau <notifications@github.com> wrote:

As @jbaiera <https://github.com/jbaiera> mentioned, we need to meet in the
middle. That is for Spark API to give us enough 'hooks' into its calls so
that we can properly create the equivalent queryDSL.
Spark SQL supports push down but not on all operations, such as count/aggs.
As such es-hadoop cannot tell whether there's a count or not involved - in
fact, all it knows from Spark is that it has to read all the data...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch-hadoop/issues/867#issuecomment-253534849>,
or mute the thread

**Comment by jbaiera** [comment]
Closing this as it seems the conversation has concluded.

**Comment by mashuai191** [comment]
@costin is the RDD support for count working now? i tried following code but it is still very very slow.
i also tried change es.scroll.size from default 50 to 1000, but it still takes long time, seems no difference. Do you have any suggestions for getting ES documents counts quickly? thanks!

--------------------------
%pyspark

from pyspark import SparkConf
from pyspark.sql import SQLContext

q ="""{
  "query": {
    "match_all": {}
  }  
}"""

es_read_conf = {
    "es.nodes" : "my_ip",
    "es.port" : "my_port",
    "es.resource" : "my_index/doc",
    "es.query" : q,
    "es.nodes.discovery" : "false",
    "es.nodes.wan.only" : "true",
    "pushdown": "true",
    "es.scroll.size": "1000"
}

es_rdd = sc.newAPIHadoopRDD(
    inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
    keyClass="org.apache.hadoop.io.NullWritable", 
    valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", 
    conf=es_read_conf)

es_rdd.count()

**Comment by jbaiera** [comment]
@mashuai191 Please avoid direct mentions to team members in comments on old issues such as these. Counting is supported via the RDD, but pushdown of the operation to Elasticsearch is not yet supported. The requisite APIs are not present in Spark to support this yet. The slowness you are most likely experiencing is due to the act of transporting all documents to Spark to be counted one by one. I advise hitting the count endpoint directly for analysis instead of running the count via Spark.
