### ISSUE TITLE
"uber mode" does not work well in elasticsearch-hadoop

### ISSUE THREAD

**Issue by wangqinghuan** [elastic/elasticsearch-hadoop#953]
I enable "uber mode" in  mapred-site.xml, as follows:
```
        <property>
                <name>mapreduce.job.ubertask.enable</name>
                <value>true</value>
        </property>
        <property>
                <name>mapreduce.job.ubertask.maxmaps</name>
                <value>20</value>
                </property>
        <property>
                <name>mapreduce.job.ubertask.maxreduces</name>
                <value>20</value>
        </property>
        <property>
               <name>mapreduce.job.ubertask.maxbytes</name>
               <value>4096</value>
         </property>
 
```
above value is 4096b. 
For example , if you hava a data set which is 4000b,then the uber mode will set . If you hava a data set which is 5000b, then the uber node will not set .   
But in practice , no matter how much  a data set is ,the uber mode will set. 
It seems like that es couldn't compute the length of split . A code block in "EsInputFormat.java" can demonstrate :
 ```
       @Override
        public long getLength() {
            // TODO: can this be computed easily?
            return 1l;
        }

```

**Comment by jbaiera** [comment]
As it stands we do indeed return just `1L` as a response from `getLength()`. The problem here is that I'm not sure if there is a way to return exact sizes of source documents from shards, especially when slicing is involved. If an estimate here is good enough for most use cases, it's possible that we could aggregate size information of the segments or shards using the cat API, or some other mechanism (hopefully json based) if it exists, then subdivide the results by the total number of slices to land somewhere in the ballpark of an accurate shard size.
