### ISSUE TITLE
Unable to save values as 'Double' using spark-elasticsearch  connector

### ISSUE THREAD

**Issue by indraneelr** [elastic/elasticsearch-hadoop#968]
I am unable to save values as double using the spark-es connector. Here's the sample code

 ```
 case class A (number1:Double, number:Double)
  test("Saving double to  elastic search"){

    spark
      .createDataFrame(Seq(A(12.0,565.524532434343),A(22.0,565.52)))
      .saveToEs("testdouble/sample")
  }
```
This saves the data, but is saved as a float type in elastic search.

The problem with this is that it fails when you read the data back because spark cannot auto cast float to double.

Here's what I am using: 
`"org.elasticsearch" % "elasticsearch-spark-20_2.11" % "5.1.2" `

My spark version is 2.0.1

Is there a way around this?

**Comment by jbaiera** [comment]
@indraneelr The problem here is connected to the way that Elasticsearch performs automatic mapping of indexed values. ES-Hadoop does not attempt to set any schema data with Elasticsearch when creating an index, but rather depends on Elasticsearch's automatic field mapping to assign reasonable values. This is expected, as the connector is built to exactly match how Elasticsearch operates and responds when you index data without a mapping using a regular REST call. If you need a field to be mapped differently when creating an index, I would suggest using the same techniques that you might use for indexing data over REST: Explicitly create the index and the mapping, disable automatic field mapping in the settings for your index. If you're creating many indices that are identical then I suggest creating index templates that define the fields you need and setting the patterns to match the names of the indices you are creating.
