### ISSUE TITLE
how to set the analyzer for a field when i usespark-elasticsearch saveToEsWithMeta save to es

### ISSUE THREAD

**Issue by tonyC2016** [elastic/elasticsearch-hadoop#975]
my question is how to set the analyzer for a field which's name is changed ,
code like as below:

val test ="性别"
val lbs: Map[String, String] = Map("create_time" -> "1491990010000",
"name" -> "年龄",
"values" -> "70后,80后,90后",
"label" -> "{values}",
"measure" ->"0.0",
"tags" ->"用户画像,灰度发布",
test->"性别,男")
sc.makeRDD(Seq((1, lbs))).saveToEsWithMeta("label_sys_label/label")

3q for help!!

**Comment by tonyC2016** [comment]
the version is 
<dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-hadoop</artifactId>
            <version>2.4.0</version>
        </dependency>

**Comment by tonyC2016** [comment]
any one can help?

**Comment by jbaiera** [comment]
@tonyC2016 Please keep questions like these on the forum until they can be decided on if they are a bug or a new feature needed. We try to keep Github for reproducible bug reports and new feature tracking only.

If you are adding new fields to an index or creating new indices in Elasticsearch from ES-Hadoop you may need to set some sort of index template so that when the new index is created it has the correct mappings and analyzers that you would expect.
